### ISSUE TITLE
Creation of the Montain range page

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#11]
La page massif sera appelée depuis le champ de recherche en page d'accueil

**Elle contiendra**

- Le nom du massif
- Une carte localisant les entrées faisant partie du massif
- La liste des cavités faisant partie du massif avec un lien vers la fiche de chaque cavité lorsqu'on clique sur le nom

**Comment by urien** [comment]
Je propose que la table de jonction massif / entry soit supprimée et que le champs avec l'id du massif soit intégré à la table entry.
En effet chaque entry ne doit être associée qu'à un massif, le fait de ne plus utiliser de table de jonction va simplifier la requette et réduire le temps de réponse

**Comment by Kurdty** [comment]
Merged (#121)
