### ISSUE TITLE
Migrate React's lifecycle methods, deprecated on next major release

### ISSUE THREAD

**Issue by Kurdty** [GrottoCenter/Grottocenter3#127]
See https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md

**Comment by bsoufflet** [comment]
@maximenathan : Tu penses quoi de cette issue ?

**Comment by Clm-Roig** [comment]
We can close I think, I didn't find any "componentWill..." functions used in the code (if I understand the initial issue correctly).

**Comment by bsoufflet** [comment]
It is an old one... @maximenathan What do you think ? We can close it I think on my side...
