### ISSUE TITLE
Association d'un réseau à un massif. Association of a network with a massif.

### ISSUE THREAD

**Issue by Souterweb** [GrottoCenter/Grottocenter3#1291]
Je me suis aperçu que sur la page du massif de la Séranne il n'y avait aucun réseau d'associé.
Pourtant le Garrel possède plusieurs entrées qui sont réunies dans le réseau intitulé "Garrel (réseau du)".
Apparemment le réseau ne s'affiche pas sur le massif car il n'a pas de coordonnées GPS. Uniquement les entrées en ont une...
En ajoutant des coordonnées au réseau (directement depuis la base de données) le réseau est maintenant attaché au massif mais cela a malheureusement cassé la page du massif. Il y a donc des retouches de développement à faire pour que les réseaux apparaissent sur la page du massif correspondant.
Suggestion de béotien : est-ce que le massif ne pourrait pas "récolter" les réseaux dont la moyenne des coordonnées des entrées est située à l'intérieur du périmètre dudit massif ? Comme ça le réseau n'aurait pas besoin de coordonnées spécifiques.

I noticed that there was no associated network on the Séranne massif page.
However, the Garrel has several entries which are grouped together in the network entitled "Garrel (réseau du)".
Apparently, the network is not displayed on the massif because it has no GPS coordinates. Only the entrances have GPS coordinates...
By adding coordinates to the network (directly from the database) the network is now attached to the massif, but this has unfortunately broken the massif page. We'll have to do some devising to make the networks appear on the corresponding massif page.
A suggestion from a philistine: couldn't the massif "harvest" networks whose average entry coordinates lie within the massif's perimeter? Then the network wouldn't need specific coordinates.

**Comment by vmarseguerra** [comment]
Fait lors de https://github.com/GrottoCenter/grottocenter-api/pull/1307

Le Garrel fait maintenant bien partie du massif de la Séranne: https://grottocenter.org/ui/massifs/8
