### ISSUE TITLE
[ADV SEARCH] Dropdown selector for country code

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#144]
Currently, the country code has to be manually entered by the user. It will be more user-friendly to load the country codes from the database and to display them in a <select> component.

**Comment by urien** [comment]
Il serait mieux d'utiliser le nom du pays dans la langue de l'utilisateur, nom issu de la table des pays dans GC, la recherche pouvant être effectuée sur le code qui est également dans cette table

**Comment by bsoufflet** [comment]
The advanced search is accessible from the home page of grottocenter

**Comment by Clm-Roig** [comment]
Dupplicate of #265 (which have more info and suggestions). I'm closing this one.
