### ISSUE TITLE
Massif result for advenced search

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#147]
![image](https://user-images.githubusercontent.com/1165144/52166772-e582e980-2711-11e9-91b2-54383d3234fd.png)
Cave and entry must be named cave networks and caves

**Comment by Kurdty** [comment]
Can you give me more informations about what I have to do ?

**Comment by urien** [comment]
Quand tu passes sur l'icone qui correspond aux infos qu'il y a dans les colonnes, la colonne avec
![image](https://user-images.githubusercontent.com/1165144/54374953-7093bf80-4680-11e9-8f78-9c4af48aecd1.png)
présente comme texte 'nombre de grottes" (en Français) alors que c'est le nombre de réseaux.
Pour cette icone
![image](https://user-images.githubusercontent.com/1165144/54375062-a20c8b00-4680-11e9-8e2f-1702d895e056.png)
Le texte est "nombre d'entrées", je me demande si nombre de cavités n'est pas mieux. mais c'est la même chose actuellement

**Comment by Kurdty** [comment]
C'est du transifex
le premier a pour clé 'Number of caves'
le second 'Number of entries'

Ces clés ne servent qu'à cet endroit.

Je ne pourrai le changer que lorsque j'aurai récupéré mon mot de passe du site transifex :)

**Comment by urien** [comment]
J'ai fait la modif sur Transifex

**Comment by urien** [comment]
Seulement sur le premier,

**Comment by Clm-Roig** [comment]
It's fixed, I'm closing.
