### ISSUE TITLE
[SWAGGER API] CSS is not loaded

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#166]
There is a css problem in the Swagger page
http://beta.grottocenter.org/ui/swagger/1

**Comment by Clm-Roig** [comment]
I can be from the following files : 
- tasks/config/copy, swaggercss section
- tasks/register **compileAssets**, copy:swaggercss

**Comment by Clm-Roig** [comment]
Now it works on AWS (on http://beta2.grottocenter.org) but not on http://beta.grottocenter.org. I don't know why currently... 

@igwall or @FatimaMachhouri what did you do on AWS to make it work ?

**Comment by Clm-Roig** [comment]
Fixed by #284 !
