### ISSUE TITLE
[RANDOM ENTRY] (x) hours is not translated

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#181]
En page d'accueil pour la cavité mise en valeur la durée apparait en Anglais alors que la traduction figure bien dans transifex
![image](https://user-images.githubusercontent.com/1165144/58378885-be3f7900-7f9b-11e9-8cf4-2c9b844c1940.png)

**Comment by Clm-Roig** [comment]
It makes the whole app crash since a few weeks, depending on the hours to translate. Must be fixed quickly!

**Comment by Clm-Roig** [comment]
J'opte pour le format **13h 55m** qui est communément utilisé sur Internet et compris dans toutes les langues. On va pas s'embêter à traduire et on garde un affichage compact et clair comme ça :slightly_smiling_face:
