### ISSUE TITLE
[RANDOM ENTRY] Organization of information to improve

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#182]
Pour la cavité mise en valeur en page d'accueil, l'organisation des informations est plus ou moins adaptée en fonction de la longueur des chaines de caractères affichés. Peut- être faudrait-il un test sur la longueur de la chaine pour déterminer l'organisation des informations

![image](https://user-images.githubusercontent.com/1165144/58378989-378b9b80-7f9d-11e9-98c5-4f9ff6cde5a0.png)
![image](https://user-images.githubusercontent.com/1165144/58379000-4f631f80-7f9d-11e9-818a-61d4a83ef972.png)
![image](https://user-images.githubusercontent.com/1165144/58379014-7883b000-7f9d-11e9-9b54-87a5c0c3602c.png)

**Comment by Clm-Roig** [comment]
J'ai quelques pistes pour ce problème (voir screen ci-dessous) : 
![Uploading Screenshot_2020-05-29_23-56-48.png…]()

1. Séparer département / région / pays => 1 élément par ligne 
2. Couper par une ellipse si le nom de l'élément est trop long 
3. Enfin, faire passer l'image dessous (au lieu d'à côté) quand on est sur un petit écran

**Comment by urien** [comment]
Oui ce serait bien mieux.

**Comment by bsoufflet** [comment]
Oui en effet !
