### ISSUE TITLE
[SEARCH] Special chars are not perfectly handled

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#205]
C'est un exemple mais cela doit correspondre à une situation générale

Lorsque recherche, dans la recherche avancée la grotte "Bois de l'Âne (Grotte du)"
On a beaucoup de difficulté à l'obtenir comme résultat de recherche
Si on met "bois de l'ane" dans l'entrée cela donne 10874 réponses souvent éloignées, si on met "correspond à au moins un critère" et pas de résultat si on met "correspond à tous les critères"

**Comment by Clm-Roig** [comment]
Pour préciser le problème, dans cet exemple, je pense qu'il y a un souci au niveau de la gestion de l'apostrophe du L. En effet, **_Bois de l'Âne (Grotte du)_** apparaît bien comme résultat dans la recherche avancée si l'on tape "âne" ou "Âne" mais dès que l'on rajoute le L apostrophe ("l'âne" ou "l'Âne"), il n'apparaît plus.

Côté client tout semble ok. 
Donc je pense que c'est une modification de la requête côté serveur (remplacement des caractères spéciaux notamment).

**Comment by Clm-Roig** [comment]
Fixed by #280 PR
