### ISSUE TITLE
[DOCUMENT] Display page

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#209]
Cette page n'existe pas sur la V2

L'adresse sera du type http://beta.grottocenter.org/ui/documents/41
avec 41 qui est l'id du document

L'acces se fera pour l'instant depuis la fiche d'une cavité ou d'un réseau
Il faudra également le rendre acessible depuis la quick searche et la recherche avancée

La page présente 1 document avec les informations suivantes
Nom du document
Nom des auteurs
Nom des cavités et des réseaux associés à ce fichier

éventuellement la date de soumission, la date de validation, la taille, l'extension. Si c'est possible afficher le document sur la page

**Comment by urien** [comment]
Attention la page document et la page BBS seront fusionnées a terme

**Comment by Clm-Roig** [comment]
La page d'un document devra prendre en compte le nouveau modèle de données, en se basant sur la table **t_document** et de tous ses liens avec les autres entités (t_grotto, t_massif etc.).

**Comment by maximenathan** [comment]
@Clm-Roig @urien 
Je vais me pencher sur cette nouvelle page
Il y a un endpoint de déjà fait pour les documents ?
Je ne vois pas sur Swagger http://beta.grottocenter.org/ui/swagger/1

Sinon je me base sur les infos donné en premier poste

**Comment by Clm-Roig** [comment]
Il y a un endpoint "bbs" qui renvoie une fiche bibliographique issue du BBS. 
Le nœud du problème c'est qu'une fois la migration de la BD effectuée, les fiches BBS seront des documents, un type d'objet bien plus "général" que simplement une fiche BBS. 

Je pense que le mieux c'est de faire un composant dans storybook qui utilise le futur modèle de données avec _document_. Tu n'auras pas de endpoint tout de suite, je m'en occuperai dès que la migration de la BD sera effectué :slightly_smiling_face: 

**Hors-sujet** : il faudrait mettre la doc Swagger à jour, elle n'est plus totalement à jour. Je vais faire ça cet aprem je pense.

**Comment by Clm-Roig** [comment]
Voici un premier jet de la maquette. Je n'en suis pas encore satisfait, ça va évoluer dans la journée certainement.

![maquette](https://user-images.githubusercontent.com/20704943/87769401-e6341080-c81d-11ea-9efa-40c71b05ee89.png)

La principale problématique, selon moi, est de déterminer ce que l'on met à gauche, dans le cadre récapitulatif et à droite, dans la partie plus détaillée.

**Comment by Clm-Roig** [comment]
J'ai fait une maquette que je peux facilement éditer ici : 
[https://wireframepro.mockflow.com/view/grottocenter_doc_view](https://wireframepro.mockflow.com/view/grottocenter_doc_view)

Je rajoute les massifs / cavités etc. de suite.

**Comment by urien** [comment]
Cela me plait bien. Les auteurs, les éditeurs et les bibliothèques sont également des entités qui ont leur propre page (ou l'auront..) Peut-être rajouter le logo pour que ce soit clair pour les utilisateurs ?

**Comment by urien** [comment]
Il faudrait rajouter la langue du document (la langue de la fiche ?) l'année, les numéro de page. Le nom du/des auteurs de la fiche.
Il me semble que les régions BBS étaient un champ déprécié ? Est ce qu'on ne mettrait pas aussi le pays et la région réelle ?
Je crois que patrick souhaite que l'identifiant BBS figure quelque part

**Comment by Clm-Roig** [comment]
> Cela me plait bien. Les auteurs, les éditeurs et les bibliothèques sont également des entités qui ont leur propre page (ou l'auront..) Peut-être rajouter le logo pour que ce soit clair pour les utilisateurs ?

C'est fait (toujours le même lien pour voir les modifs) 

> Il faudrait rajouter la langue du document (la langue de la fiche ?) l'année, les numéro de page. Le nom du/des auteurs de la fiche.
> Il me semble que les régions BBS étaient un champ déprécié ? Est ce qu'on ne mettrait pas aussi le pays et la région réelle ?
> Je crois que patrick souhaite que l'identifiant BBS figure quelque part

Je m'en occupe demain, c'est noté.

**Comment by Clm-Roig** [comment]
>  Il me semble que les régions BBS étaient un champ déprécié ? 
Oui à la création du document il ne sera plus possible de rentrer ce champ. Par contre il faut pouvoir l'afficher pour ceux qui l'ont. 

J'ai fait tout le reste, c'est bon !

**Comment by urien** [comment]
Parfait. il faudra trouver un truc pour afficher les régions "BBS" et le pays, la région réels. peut être que ce sera l'un ou l'autre en fonction de ce qui est disponible dans la base ?. Je ne crois pas qu'on puisse les mettre avec les entités liées.  Mais cela me semble bien pour réaliser la page réelle

**Comment by Clm-Roig** [comment]
Il faudrait faire ce travail de correspondance côté base de données éventuellement. Pour l'instant, on affiche l'info qu'on a, que ce soit une localisation "standard" ou une région BBS.
