### ISSUE TITLE
Problème d'affichage sous safari

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#241]
Sur la beta grottocenter, sur Safari 12.1.2 (MacOS), il y a un bug d'affichage de la colonne de gauche

**Comment by maximenathan** [comment]
Probablement un bug sur la hauteur des icons :

![image](https://user-images.githubusercontent.com/7127156/79853300-270bbd00-83c8-11ea-82bd-5d15686be6ed.png)
