### ISSUE TITLE
[MAP] Improve clusters

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#243]
Je retranscrit ici une remarque formulée par un utilisateur
"
1- Les « bulles » présentant le nombre de cavités ne sont pas liées à des frontières réelles 
2- les bulles se déplacent quand on zoom (voir pj europe)
3- les bulle se déplacent quand on ne fait que « pan »  (voir pj afrique)
4- c’est valable même aux echelles les plus grandes

exemple 1: sur la première ve, il y a 19167 cavité dans le sud de la france, et zéro en allemagne. Si je zoom sur la france, tout d’un coup apparait 52 cavité en allemagne.
par ailleurs, en italie, si je zoom sur 2175, d’un coup, le point disparait (split en deux) (normal, c’est le barycentre).
example 2: Sur l'autre carte, il n’y a pas de cavité en egypte, et en se déplacant, elles apparaissent (pour redisparaitre plus tard)

du coup, a. on est toujours en train de zoomer et recentrer à droite et à gauche pour « pêcher » les grottes. 
et b. on voit une zone interessante (plein de grottes), on zoome, et on se rend compte que la zone est vierge (elles disparaissent d’un coup). mais si on zoome encore, des cavité peuvent réapparaitre là où avant il n’y avait rien. 
Donc c’est particulièrement inutile et ereintant, car cela force à « paner » pour vérifier l’entièreté d’une zone et voir toutes les cavités de la zone. d’autre part  on s’imagine qu’il y a des grottes là où il n’y en a pas

peut-être faudrait il diminuer le seuil d’aggrégation des cavités, ou mieux utiliser un procédé qui différent, comme une heatmap qui conserve la geographie (voir pj corse)"
![Capture d’écran 2020-04-23 à 11 26 56](https://user-images.githubusercontent.com/1165144/80085162-26a22c00-8558-11ea-9c50-d1ea338a8401.jpg)

**Comment by maximenathan** [comment]
Exemple trouvé par Benjamin: https://deutchland.maps.sensor.community/#4/39.77/40.35

**Comment by Ospeleo** [comment]
je viens de tester https://deutchland.maps.sensor.community/#4/39.77/40.35 
j'ai l'impression qu'il y a le même probleme avec les cluster.

sur http://bl.ocks.org/tnightingale/4668062
j'ai l'impression que cela marche de manière plus "logique"

**Comment by bsoufflet** [comment]
@Ospeleo http://bl.ocks.org/tnightingale/4668062 est un bel exemple qui semble en effet mieux que https://deutchland.maps.sensor.community ! pas facile de trouver des exemples bien de clustering.

**Comment by bsoufflet** [comment]
@Ospeleo : C'est deployé sur http://beta2.grottocenter.org . DIs nous ce que tu en penses !!

**Comment by Ospeleo** [comment]
;)

![Capture d’écran 2020-11-28 à 19 28 06](https://user-images.githubusercontent.com/12714994/100528915-f8509300-31af-11eb-9b5b-cbb957e48831.jpg)

**Comment by urien** [comment]
Benjamin nous a indiqué : "Il semble y avoir un bug en ce moment sur beta2. Si on était précédemment connecté, on se retrouve avec une page rouge et on doit absolument vider les cookies de connexion pour accéder à l'app..."

**Comment by Ospeleo** [comment]
Ok, merci.
J'ai testé (iphone + navigateur). C'est beaucoup mieux.

quelques remarques:
- Le chargement des hexagones se fait en deux passes: une première avec que des hexagones blancs; une seconde où ils changent de couleur et passent à différentes intensité de gris. (ma connexion est mauvaise, je suis à l'étranger)
Ne serait-il pas possible de leur calculer la couleur, et leur style, dès la première fois?

- L'echelle d'intensité pourrait être modifiée: il y a plusieurs hexagone gris foncés en Centrafrique (avec une seule grotte à chaque fois), et des hexagones en majorité blancs sur le vercors...

- d'autre part, en fonction de ce que l'on voit (quand on translate (pan). l'echelle pourrait etre fixe (log?)

- peut-etre que si on clique sur un hexagone, alors cela pourrait zoomer directement sur CET hexagone (en ce moment, il ne se passe rien si on clique sur un hexagone. L'hexagone change de taille (a:hover), mais il n'y a pas d'action associée -> soit il ne change pas de taille / soit il y a une action si on clique, mais là, c'est bancal

**Comment by maximenathan** [comment]
Merci pour tes retours

Pour répondre à tes remarques:

- Tout est fait en même temps. C'est la librairie graphique (a base de [d3](https://d3js.org/)) qui s'en occupe... A voir si c'est possible d'optimiser mais ca risque d'être long pour pas grand chose.

- L'echelle d'intensité se base sur ce qui est actuellement affiché. Quand on zoom, c'est donc normal de retrouver des polygones petits & claire même dans le Vercors. La nuance de couleur est définit par default avec d3.scaleLinear.
Ca fait quelque chose comme ca (ou d'autres [exemples](https://www.d3indepth.com/scales/)):
```js
const linearScale = d3.scaleLinear()
  .domain([0, 1000]) // min - max ou max est le nombre de cavités maximum
  .range(['white', 'brown']);

linearScale(0);   // returns "white"
linearScale(500);   // returns "50%white 50/brown"
linearScale(1000);  // returns "brown"
```
On peut très bien définir un comportement different mais c'est très chronophage à faire. Si tu as une idée que tu veux que je test, avec plaisir. 

- Pas sur de comprendre. J'y est peut etre répondu juste avant

- Tu peux double clique pour zoom sur une zone. J'ai rajouté un tooltip sur le hover pour indiquer le nombre de cavités/réseaux. Ca arrivera dans la semaine
