### ISSUE TITLE
Problems with advenced search 

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#253]
Olivier qui utilise Safari sur MacOs me dit que la recherche avancée ne fonctionne pas. Voila des copies d'écran de ce qu'il obtient. par contre la recherche rapide fonctionne.
C'est la même chose sur Firefox sous W10

![unnamed](https://user-images.githubusercontent.com/1165144/80722504-b5d2b500-8aff-11ea-8273-97aec949ab56.jpg)
![recherche-avancee](https://user-images.githubusercontent.com/1165144/80722924-38f40b00-8b00-11ea-94d5-d98c02af1643.gif)

**Comment by Clm-Roig** [comment]
Normalement c'est fixé par la PR #252. C'est mergé sur #rc, ce sera actif au prochain déploiement.

**Comment by Clm-Roig** [comment]
C'est bon c'est en ligne !
