### ISSUE TITLE
[ADV SEARCH] Scroller jusqu'aux résultats de recherches après une recherche (hors écran sur mobile)

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/Grottocenter3#260]
sur mon téléphone, lorsque je tape un mot à rechercher, je clique sur « recherche »
rien ne se passe, car c’est tout en bas de la page, hors écran, que les résutlats s’affichent. Au début, je pensais même que la fonction ne marchait pas

il faudrait qu’une fois les résultats calculés, l'utilisateur soit redirigé vers l’ancre des résultats, un peu plus bas.

**Comment by ClemRz** [comment]
I'll be working on this one.

**Comment by ClemRz** [comment]
Branch: `feature/260_scroll-to-search-results`

**Comment by ClemRz** [comment]
PR#502

**Comment by Clm-Roig** [comment]
Fixed by #502 in February, I'm closing.
