### ISSUE TITLE
Titre h1 trop gros

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/Grottocenter3#261]
la typo des titres est trop grande.

Sur Iphone
![Grottocenter v3 2](https://user-images.githubusercontent.com/12714994/81404503-ecc74d00-9135-11ea-81f9-cefcf226de9c.png)

Sur Navigateur (safari
![Capture d’écran 2020-05-08 à 14 12 37](https://user-images.githubusercontent.com/12714994/81404530-05cffe00-9136-11ea-8224-7154e601854b.jpg)

**Comment by Clm-Roig** [comment]
C'est corrigé sur mon travail en cours. Ce sera donc actif dans les prochains déploiement normalement 🙂

**Comment by Clm-Roig** [comment]
Fixed by #308, I'm closing.
