### ISSUE TITLE
Format d'affichage d'une fiche cavité a

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/Grottocenter3#264]
Dans le recherche normale, la feuille de style ou la gabarit « mobile » pourrait être modifié pour les résultats de grotte. C’est vraiment illisible sur petit écran.

Une seule colonne, Nom, propriétés, descriptif, plan, carte, liens de partage (par exemple)

![GrottoCenter 2 1 1 La base de données Wiki faite par les spéléos, pour les spéléos  Azirou (Aven de l')  Aven de la Bergerie d'A](https://user-images.githubusercontent.com/12714994/81404838-b50cd500-9136-11ea-96e7-4fd01bbf1321.png)

**Comment by Clm-Roig** [comment]
Cette page provient de Grottocenter 2 (suite à une redirection depuis la recherche).
A terme, on fera une redirection vers la nouvelle page des entrées de la v3, quand celle-ci sera complète.
