### ISSUE TITLE
[QUICK SEARCH] Plusieurs problèmes

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/Grottocenter3#267]
A partir de la page d'accueil beta2, la recherche Quicksearch a un comportement defectueux

cas 1
- si je tape "berger", et je clique sur une cavité proposée, la carte se centre sur cette cavité
- si juste après, je cherche autre chose, "bu56", et je clique sur la cavité, la carte ne se centre pas sur la nouvelle cavité

cas 2
- si je tape "bresil", et je clique sur un documents, je suis transporté vers une page blanche et l'url m'indique que j'ai été renvoyé vers une page "massif"
- si je fais juste après une apres quicksearch, et que je clique sur un autre document, j'arrive sur la page erreur. Notez l'url "massif"

cas 3
- si je tape "tahiti", les quickresults proposés n'ont pas grand chose à voir, pour certains

je n'ai pas fais d'autres tests

![Capture d’écran 2020-05-09 à 13 58 21](https://user-images.githubusercontent.com/12714994/81473232-53fc0480-91fd-11ea-8d74-7c8f32380f11.jpg)

**Comment by Clm-Roig** [comment]
Effectivement, pas mal de soucis avec cette nouvelle version;, merci pour le retour. 

cas 1 : je ne connais pas cette partie du code personnellement. 

cas 2 : j'ai identifié le souci, il est [ici ](https://github.com/GrottoCenter/Grottocenter3/blob/6f465518569230ca55fd1cf3a1d9b8ea37079ee1/assets/js/react/features/QuickSearch.jsx#L45). Il faut changer l'url par /bbs dans le cas bbs évidemment...

cas 3 : je comprends ce problème, ça vient de la "distance" qu'on autorise pour matcher des résultats. On autorise une distance de 1, c'est-à-dire que la recherche peut retourner des résultats avec un caractère différent. Ça permet de corriger des fautes de frappe par exemple mais dans le cas "tahiti" ça retourne des choses peu pertinentes j'en conviens 😕 Il faudrait que les résultats à une distance de 1 soit bien moins classés et apparaissent en dernier, je crois que ce n'est pas le cas actuellement.

**Comment by Clm-Roig** [comment]
Cas 2 fixé par la PR #277 
Je me permets de fermer et de créer 2 nouvelles "issues", une pour chaque problème restant :slightly_smiling_face: Merci encore pour le retour !

**Comment by Ospeleo** [comment]
cas 3: des résultats en italie (taciti) n'ayant rien à voir avec "tahiti" sont présentés avant des résultats plus pertinent (Hawaii).
C'est un choix de grottocenter d'autoriser des divergences d'une lettre avec le terme recherché.
C'est donc une fonctionalité, pas un bug ;)

ps: à rapprocher de https://github.com/GrottoCenter/Grottocenter3/issues/265#issuecomment-626214980

**Comment by Clm-Roig** [comment]
Ok je comprends mieux, merci ! Je créé une nouvelle issue de suite et je mentionne la 265, c'est lié effectivement.
