### ISSUE TITLE
[ADV SEARCH] Nombre de résultat différent entre BBS/filemaker et BBS/grottocenter

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/Grottocenter3#269]
Sur une recherche par auteur "testa", il y a 54 résultats via grottocenter vs. 47 via BBS originale.
recherche "orchampt": 14 vs. 13

Les recherches par auteur grottocenter sont plus fournies. et justes.
(cause: Grottocenter fait des recherche par chaine de texte, alors que filemaker doit utiliser des mots. les manques d'espaces le contrarie)

Effet inverse sur les recherche par pays sur cet exemple: "cameroun". Filemaker propose deux résultats de plus (mot présente dans les cross-index pays, que grottocenter a omis à mon avis.)

**Comment by Clm-Roig** [comment]
Pour les auteurs, la recherche "floue" qui permet des fautes de frappe où d'ignorer les espaces par exemple, est donc un plus value pour nous, merci pour le retour !

Concernant les pays, on se référera à l'issue #265 qui en parle déjà : je ferme cette issue donc.
