### ISSUE TITLE
[ENTRY] Page crashes due to map fullscreen button

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#294]
Sur beta.grottocenter.org lorsque je souhaite afficher une entrée la page se recouvre immédiatement d'une page d'erreur avec ce code
![2020-06-04](https://user-images.githubusercontent.com/1165144/83720983-75081780-a63a-11ea-9b1f-48321b567b42.png)

**Comment by Clm-Roig** [comment]
Le problème est connu, on en discute et on cherche des solutions. Au pire des cas, on peut retirer le module qui fait tout planter (il permet juste d'afficher un bouton "plein écran" sur la carte) ?

**Comment by urien** [comment]
On peut attendre.
Je souhaite communiquer sur la nouvelle version car il y a pas mal de nouvelles choses à découvrir. Cela peut attendre que ce soit réglé.

**Comment by Clm-Roig** [comment]
Fixed (temporarily) by #298 
To be deployed today
