### ISSUE TITLE
bbs recherhce

### ISSUE THREAD

**Issue by Ospeleo** [GrottoCenter/Grottocenter3#304]
un exemple:
recherche pays: "Chine": 2 resultats
China: 1200
Il doit y avoir d'autres exemples de mix des noms de pays en deux langues dans la bdd

**Comment by Clm-Roig** [comment]
C'est lié à #265, je copie/colle là-bas le message et je ferme ici. 
Pour faire court, ce problème va disparaître avec le nouveau modèle de gestion des zones géographiques qui sera mis en place dans les mois à venir. On avance sur la base de données pour l'instant, la suite viendra après :slightly_smiling_face:
