### ISSUE TITLE
[DOCUMENT] Validation page

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#309]
Un document est soumis par n'importe quel utilisateur authentifié de Grottocenter. Une fois le document soumis, il est dans un état "en attente de validation". 

Les coordinateurs / validateurs peuvent, à tout moment, consulter la liste des soumissions de documents par les utilisateurs. Ils peuvent **trier** les soumissions par : 
- document parent
- code région du document 
- date de soumission 

### **Proposition de maquette, à discuter :** 

![maquette_validation](https://user-images.githubusercontent.com/20704943/87061368-f5a6ce80-c20b-11ea-928c-8e3531eb223e.png)

Ils ont le choix de valider ou de refuser la soumission, avec un commentaire motivant ce choix (commentaire facultatif en cas de validation, obligatoire en cas de refus). 

La validation ou le refus de la soumission se ferait en bas de page de l'aperçu du document (voir issue 
#209). Ainsi, on serait obligé de voir le document pour prendre une décision.

### **TODO et à ajouter ici : maquette de l'interface de validation au pied d'un document**

Il y aurait 3 rôles (indirectement) liés à cette fonctionnalité : 
- N'importe quel **utilisateur authentifié** peut créer une fiche document. Elle est alors dans l’état “en attente de validation” (voir PR #308 qui propose un formulaire de soumission de document dans sa première version).
- Un **coordinateur** peut également valider les fiches créées par les utilisateurs.
- Un **administrateur** peut attribuer le rôle “contributeur” à un compte existant.

**Comment by maximenathan** [comment]
Il faut être sur que c'est suffisant niveau feature (qu'on est pas besoin de trier, rechercher, multi selection de documents pour valider...)
Mais si une version simple comme celle ci est suffisante c'est parfait

On y accède avec un compte admin via le menu de gauche ?

**Comment by bsoufflet** [comment]
@urien tu pourrais dire ce que tu en penses au niveau features ?

**Comment by urien** [comment]
Je rejoins la préoccupation de de Maxime : on risque d'avoir des centaines de lignes assez vite : une personne qui se met à faire des analyses va en faire 50 en une demi-journée.
Ce serait donc utile d'avoir un système de pagination. On pourrait remplacer la colonne "aperçu" par "pays" de manière à ce qu'il soit possible de faire une sélection sur ce critère. Et pour valider la fiche cela reviens à l'éditer, on pourrait y accéder en cliquant sur le nom du document comme on le fait pour la visualiser.

**Comment by Clm-Roig** [comment]
- Le système de pagination est bien présent (en bas à gauche), comme pour la recherche avancée. 
- Oui pour cliquer sur toute la ligne plutôt qu'une colonne "Aperçu".
- Oui pour l'ajout du Pays à la place d'Aperçu. 
- Oui pour le filtre par pays.

Je pense qu'un filtre par date de soumission peut être utile : 
- si on veut valider une fiche très rapidement, qui vient d'être soumise, on affiche les plus récentes. 
- si on veut valider les plus vieilles (par logique de "premier arrivé, premier servi"), on affiche les plus vieilles.

>
> Il faut être sur que c'est suffisant niveau feature (qu'on est pas besoin de trier, rechercher, multi selection de documents pour valider...)

Je suis totalement d'accord, l'issue est là pour en parler.

>
> On y accède avec un compte admin via le menu de gauche ?

ça me paraît être une bonne idée oui. Je pensais également à un lien depuis la page "Dashboard" qui est accessible à l'adresse http://beta.grottocenter.org/ui/ .

**Comment by Clm-Roig** [comment]
### Rôles et utilisateurs
Il y aurait 3 rôles (indirectement) liés à cette fonctionnalité : 
- N'importe quel **utilisateur authentifié** peut créer une fiche document. Elle est alors dans l’état “en attente de validation” (voir PR #308 qui propose un formulaire de soumission de document dans sa première version).
- Un **coordinateur** peut également valider les fiches créées par les utilisateurs.
- Un **administrateur** peut attribuer le rôle “contributeur” à un compte existant.

**Comment by Clm-Roig** [comment]
La maquette listant les soumissions de documents à été mise à jour après discussions.
