### ISSUE TITLE
BBS number

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#310]
Le nombre de fiches BBS ne s'affiche pas sur beta
![bbs](https://user-images.githubusercontent.com/1165144/87643796-99800500-c74b-11ea-932b-2bff4dfa18a1.png)

**Comment by Clm-Roig** [comment]
Ça fonctionne chez moi sur beta et beta2

**Comment by urien** [comment]
C'est bon pour moi aussi
