### ISSUE TITLE
[Authentication][Tech] Review Auth & Rights for users (use Redux)

### ISSUE THREAD

**Issue by maximenathan** [GrottoCenter/Grottocenter3#351]

**Comment by Clm-Roig** [comment]
Je suis dessus actuellement sur la branche **improvement/redux_auth**. Petit point de là où j'en suis dans mes réflexions : 

- Le token est stocké dans Redux dès qu'on se loggue.
- Les données du comptes de l'utilisateur (rôles et nickname) contenues dans le token sont décodées et stockés dans Redux dès qu'on se loggue.
- Le header d'Authorization contenant le token est stocké dans Redux dès qu'on se loggue.
- Le localStorage n'est utilisé que pour garder la connexion entre différentes sessions sur le même navigateur.
- Le AuthHelper n'utilise plus le localStorage mais demande le store Redux **auth** dans toutes ses fonctions utilitaires. 
- Les actions qui appelaient **AuthHelper.getAuthHttpHeader()** vont directement le chercher dans le Redux store grâce à la fonction **getState()** auxquelles elles ont accès.

**Comment by Clm-Roig** [comment]
@maximenathan @bsoufflet un avis sur la question ? :slightly_smiling_face:

**Comment by maximenathan** [comment]
Pardon j'ai pas vu le ping :)
Je regarde demain!

**Comment by maximenathan** [comment]
Tu peux me montrer à quoi ressemblerait un composant avec différent element à afficher en fonction du role ?

**Comment by Clm-Roig** [comment]
> Tu peux me montrer à quoi ressemblerait un composant avec différent element à afficher en fonction du role ?

Rien ne change à ce niveau-là, on lit le store (au lieu du token comme avant) pour déterminer si l'utilisateur a le bon rôle : si oui on affiche sinon non. 
C'est principalement une question de réorganisation du code, y a pas vraiment de nouvelles features :slightly_smiling_face: 

A moins que quand tu demandes "à quoi ressemblerait un composant" tu parles du code ? Je rajoute ça à ce message dans un instant.

**Comment by maximenathan** [comment]
J'irai encore un peu plus loin avec une abstraction en plus
Par exemple un hook `usePermissions`

A utiliser :
```js
const { isModerator, isAuth, isUser } = usePermissions()
```

A part si @bsoufflet a une idée plus précise sur la gestions des roles?
Mais je pense que dans le cas de GC ca devrait le faire!

**Comment by Clm-Roig** [comment]
Le hook me semble pas mal, ça allège encore un peu la syntaxe et on fait l'accès au store **auth** que dans le hook (au lieu de le faire dans tous les composants comme dans ma proposition actuelle).

**Comment by maximenathan** [comment]
Oui ca change pas grand chose a part alleger un peu la code base

**Comment by Clm-Roig** [comment]
J'en suis là pour le moment, y a peut-être des améliorations à apporter (c'est mon premier hook custom): 

### usePermissions.js
```javascript
import { useSelector } from 'react-redux';

import { pathOr } from 'ramda';

// =========================================

const isTokenExpired = (authState) => {
  try {
    if (authState.authTokenDecoded.exp < Date.now() / 1000) {
      return true;
    }
    return false;
  } catch (err) {
    return false;
  }
};

const hasRole = (authState, roleName) => {
  const groups = pathOr(null, ['authTokenDecoded', 'groups'], authState);
  if (groups === null) return false;
  return groups.some((g) => g.name === roleName);
};

// eslint-disable-next-line import/prefer-default-export
export function usePermissions() {
  const authState = useSelector((state) => state.auth);
  return {
    isAdmin: hasRole(authState, 'Administrator'),
    isAuth: authState.authTokenDecoded !== null && !isTokenExpired(),
    isModerator: hasRole(authState, 'Moderator'),
    isTokenExpired: isTokenExpired(),
    isUser: hasRole(authState, 'User'),
  };
}
```

### Exemple dans MenuLinks.js
```javascript
import React from 'react';
import { List } from '@material-ui/core';
import Item, { DocumentItems } from './Items';
import { Icon } from './styles';

import { usePermissions } from '../../../hooks';

const MenuLinks = () => {
  const permissions = usePermissions();
  return (
    <List component="nav" aria-label="main mailbox folders">
      <Item
        ItemIcon={() => (
          <Icon src="/images/sidemenu/home.png" alt="home icon" />
        )}
        label="Home page"
        href="/"
      />
      {permissions.isAuth && (
        <Item
          ItemIcon={() => (
            <Icon src="/images/sidemenu/dashboard.png" alt="dashboard icon" />
          )}
          label="Dashboard"
          href="/ui"
        />
      )}
      <Item
        ItemIcon={() => (
          <Icon src="/images/sidemenu/search.png" alt="search icon" />
        )}
        label="Advanced search"
        href="/ui/search"
      />
      <Item
        ItemIcon={() => <Icon src="/images/sidemenu/loc.png" alt="map icon" />}
        label="Map"
        href="/ui/map"
      />
      <Item
        ItemIcon={() => (
          <Icon src="/images/sidemenu/wrench.png" alt="wrench icon" />
        )}
        label="Toolbox"
        href="#"
      />
      <DocumentItems
        isModerator={permissions.isModerator}
        isUser={permissions.isUser}
      />
    </List>
  );
};

export default MenuLinks;


```

**Comment by maximenathan** [comment]
Oui ça me semble pas mal!
