### ISSUE TITLE
[GROUPS] Some groups don't load (seems random)

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#356]
Quand on veut afficher les pages des groupes, cela fonctionne pour certains et pas pour d'autres : 
Les Vulcains ça marche ( https://beta.grottocenter.org/ui/groups/2 ) 
mais pas l'Alpina ( https://beta.grottocenter.org/ui/groups/388 ). 
SCM ne se charge pas: https://beta.grottocenter.org/ui/groups/422 
La page du GSI se charge bien ( https://beta.grottocenter.org/ui/groups/428 ), 
celle du SCAL aussi ( https://beta.grottocenter.org/ui/groups/56 ), 
mais pas celle du GSUM ( https://beta.grottocenter.org/ui/groups/495 ).

**Comment by urien** [comment]
Quand on est dans la fiche permettant de rajouter un document, pour certains groupes quand on clique sur leur nom cela affiche #2077 - undefined

**Comment by Clm-Roig** [comment]
C'est un problème de données. Certains groupes n'ont pas de **name** avec l'attribut **isMain**... A voir avec Vincent.

**Comment by Clm-Roig** [comment]
J'ai identifié le problème de chargement, j'y travaille.
