### ISSUE TITLE
[DB] Add a MULTIPOLYGON column to the massif table

### ISSUE THREAD

**Issue by bsoufflet** [GrottoCenter/Grottocenter3#411]
With a MULTIPOLYGON column we could draw the massif on a map and then use the [ST_INTERSECTS](https://postgis.net/docs/ST_Intersects.html) function of postgis to quickly and easily retrieve all the entrances which are inside the polygone of the massif.

**Comment by urien** [comment]
Un massif est une unité géographique qui peut être défini par un polygone sur une carte.
Il peut être associé à des documents, à des organisations et à des cavités
Il est possible d'avoir des massifs imbriqués correspondant à des niveau de zoom différent
par exemple Alpes > Chartreuse > Grand Som > Vallon des Eparres
Mais il également possible d'avoir des massifs correspondant à d'autres découpages
par exemple le périmètre du parc Naturel des Grand Causses ou le bassin Hyrdaulogique de la source de Miolène
Pour chacun de ces massifs il faut qu'une procédure automatique, utilisant les fonctionnalités de PostGis, associent les cavités qui se trouve dans le périmètre défini par le polygone du massif

**Comment by Clm-Roig** [comment]
J'ai résolu ça sur la prod hier et il me semble qu'en dev et test c'était ok (@lageta tu confirmes ?). Si oui, on peut fermer.

**Comment by lageta** [comment]
> J'ai résolu ça sur la prod hier et il me semble qu'en dev et test c'était ok (@lageta tu confirmes ?). Si oui, on peut fermer.

On n'utilise pas [ST_INTERSECTS](https://postgis.net/docs/ST_Intersects.html) mais c'est bien une colonne MULTIPOLYGON pour stocker les massifs désormais 👍
