### ISSUE TITLE
RDF(LOD) mapping in API with JSON-LD : add keys @id, @type, @context

### ISSUE THREAD

**Issue by jmvanel** [GrottoCenter/Grottocenter3#416]
Je fais ici une première suggestion, dans une approche incrémentale.

Pour rapport au massif n°3 ,  http://beta.grottocenter.org/api/v1/massifs/3
Ajouter:
A la racine:
```json
  "@context": "https://ontology.uis-speleo.org/grottocenter.org_context.jsonld",
  "@id": "12",
  "@type": "http://purl.org/dc/terms/Location"
```
  ( et alors on pourrait enlever "id": 12, )

Au niveau d'une grotte:
 ```json
     "@base": "entrances/",
     "@id": "83",
     "@type": "https://ontology.uis-speleo.org/ontology/#UndergroundCavity"
```

 Le `@context` n'est pas encore présent ici "https://ontology.uis-speleo.org/grottocenter.org_context.jsonld" , mais ça n'empêche pas de l'ajouter ...

Voir article (en chantier) "La technologie JSON-LD pour enrichir les API JSON"  = <http://semantic-forms.cc:1952/ldp/1605792725242-8653856520870337>

**Comment by urien** [comment]
Il faudrait regarder les outils Node existants. Par exemple https://www.npmjs.com/package/jsonld

**Comment by jmvanel** [comment]
C'est une implémentation des API du W3C comme il en existe dans les principaux langages, et que je connais bien pour l'utiliser sur la JVM .
Ces API permettent de traduire RDF <--> JSON-LD, et de transformer du JSON-LD vers les 4 formes de JSON-LD: Expanded Document Form, Compacted, Flattened, Framed. Cela ne permet pas de créer du RDF ou du JSON-LD là où il n'y en a pas.

Liens vers les specs :
https://www.w3.org/TR/json-ld/
https://www.w3.org/TR/json-ld11-api/
https://www.w3.org/TR/json-ld11-framing/

Outils en ligne de validation:
[JSON-LD Playground](https://json-ld.org/playground/), [RDF distiller](http://rdf.greggkellogg.net/distiller?command=serialize).

A noter: cette librairie JS n'implémente que la spec 1.0 .

**Comment by jmvanel** [comment]
Dans Grottocenter3 on dirait que ça se passe dans 
api/services/MappingV1Service.js
