### ISSUE TITLE
[MAP] Ressource en 404

### ISSUE THREAD

**Issue by louis-cuny** [GrottoCenter/Grottocenter3#433]
Sur Firefox et chrome, lorsque je me ballade sur la carte. Le message d'erreur "The ressource you are looking was not found - Fetching map" ne cesse d'apparaitre.
En effet, dans la console j'ai des appels ajax qui retournent des 404.

Exemple :
https://beta.grottocenter.org/api/v1/geoloc/findByBounds?sw_lat=42.39912215986002&sw_lng=-2.5817871093750004&
ne_lat=50.233151832472245&ne_lng=9.799804687500002&zoom=7

![image](https://user-images.githubusercontent.com/13121784/100543233-351f9700-324f-11eb-9727-515e893b4711.png)

**Comment by louis-cuny** [comment]
Cette erreur semble provoquer la non apparition des éléments sur la carte.

**Comment by bsoufflet** [comment]
Tu dois etre encore sur l'ancienne Map de la v3 de grottocenter... La nouvelle map est dispo depuis ce weekend sur http://beta2.grottocenter.org (https://beta.grottocenter.org se met à jour plus tard à cause de mise en cache par cloudflare)

**Comment by louis-cuny** [comment]
En effet, le soucis n'est pas présent sur beta2.
Je ferme le ticket
