### ISSUE TITLE
Formulaire de contact HS

### ISSUE THREAD

**Issue by louis-cuny** [GrottoCenter/Grottocenter3#434]
J'ai tenté d'utiliser le formulaire de contact.
A la soumission, on m'a retourné une page d'erreur google 

![image](https://user-images.githubusercontent.com/13121784/100548090-bd5f6580-326a-11eb-9484-63ea02431850.png)
![image](https://user-images.githubusercontent.com/13121784/100548094-c8b29100-326a-11eb-95a5-134bd0aca85c.png)

**Comment by urien** [comment]
Merci Louis, je vais m'en occuper

**Comment by urien** [comment]
C'est fait, j'ai mis en place une solution qui fonctionne.
