### ISSUE TITLE
[QUICK SEARCH] Impossible d'accéder à un résultat

### ISSUE THREAD

**Issue by louis-cuny** [GrottoCenter/Grottocenter3#435]
Lorsque j'effectue une recherche rapide, la liste de résultats apparait.

Lorsque je clique sur un résultat la liste disparait et la search bar vidée.
Même comportement si je descend dans les résultats avec les fleches et tappe Enter.

Peut être manque-t-il un simple lien ?

De +, si je retappe "Ours" par exemple j'ai un warning  qui apparait dans la console.

![image](https://user-images.githubusercontent.com/13121784/100551610-0bcc2e80-3282-11eb-94a6-d8a95547bb58.png)

**Comment by Clm-Roig** [comment]
La redirection pour certains résultats de la recherche rapide a été désactivée car les pages de "détails" ne fonctionnaient plus. C'est désormais réparé, on peut remettre la redirection en place !
