### ISSUE TITLE
[ENTRANCES API] /entrances/count KO 504

### ISSUE THREAD

**Issue by jmvanel** [GrottoCenter/Grottocenter3#460]
https://beta.grottocenter.org/api/v1/entrances/count =>
Error 504 Ray ID: 60532f7fcb6ebc24 • 2020-12-21 17:06:01 UTC Gateway time-out

Alors que https://beta.grottocenter.org/api/v1/documents/count fonctionne :)

**Comment by Clm-Roig** [comment]
Je corrige ça, c'est un problème d'url => le "v1" a été oublié dans l'url que l'on utilise actuellement, je vais le rajouter.
