### ISSUE TITLE
[ENTRANCES API] Sensible entrance error management (ex: entrance of id 13)

### ISSUE THREAD

**Issue by jmvanel** [GrottoCenter/Grottocenter3#461]
En mettant au point mon script de chargement, je suis tombé sur un trou dans la numérotation: https://beta.grottocenter.org/api/v1/entrances/13

C'est plutôt un abîme sans fond :
Error 504 Ray ID: 60606cbd4908072e • 2020-12-23 07:39:44 UTC
Gateway time-out

**Comment by bsoufflet** [comment]
La cavité 13 est indiqué comme sensible et donc non accessible via l'API publique.

**Comment by jmvanel** [comment]
Merci @bsoufflet ;
Idéalement le serveur renverrait un message explicite,
de préférence en JSON du genre
```json
{ "message":
"La cavité est indiquée comme sensible et donc non accessible via l'API publique."}
```
plutôt que faire attendre le client avec un timeout.

mais ce qui serait chouette serait de renvoyer quelque de divulgable sur cette cavité.
Même chose pour les personnes, il n'y a pas d'API je crois, mais j'en ai entendu parler ...

**Comment by bsoufflet** [comment]
Oui en effet, on peut laisser ce ticket github ouvert pour traiter cela :
- message indiquant que la cavité est sensible 
- informations basiques sur celle-ci (pas de localisation, ...)

**Comment by Clm-Roig** [comment]
> Oui en effet, on peut laisser ce ticket github ouvert pour traiter cela :
> 
>     * message indiquant que la cavité est sensible
> 
>     * informations basiques sur celle-ci (pas de localisation, ...)

A part la **latitude** et la **longitude**, y a-t-il autre chose à cacher ? Je suis dessus là.

**Comment by urien** [comment]
Oui, il faut aussi masquer l’accès

**Comment by Clm-Roig** [comment]
> Oui, il faut aussi masquer l’accès

Qu'est-ce que l'accès en terme de données ? Les textes écrits par les utilisateurs permettant d'y accéder ? (table **t_location** j'imagine ?)

**Comment by urien** [comment]
Oui je pense, il doit y avoir une table de jonction car il peut y avoir plusieurs entrées dans t_location

**Comment by Clm-Roig** [comment]
ok je m'occupe de ça et je le pousse dans l'heure
