### ISSUE TITLE
Magazine

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#462]
Vincent a créé un type Magazine alors que dans le modèle nous avons Collection qui correspond au type prévu dans DCMI.
Il faudrait affecter l'id de Collection à tout ce qui est déclaré comme Magazine.
C'est relativement urgent car les utilisateurs sont en train de recréer les Collections.

**Comment by bsoufflet** [comment]
C'est quelque chose à faire en base de données via une requete SQL ? Si c'est le cas je peux m'en occuper...
Peux tu me donner plus de détails ? Merci

**Comment by urien** [comment]
Merci Benjamin,
Voila les types qu'on a retenu pour les documents.
![image2](https://user-images.githubusercontent.com/1165144/103149599-256e7200-476b-11eb-9c3f-f953f335ffc9.png)
![image1](https://user-images.githubusercontent.com/1165144/103149600-26070880-476b-11eb-8387-8980c46339d5.png)
dans la table t_type
Vincent a créé un type supplémentaire (Magazine) et il a attribué ce type à tout ce qui devait être avec un type "Collection"
Reviens vers moi si ce n'est pas clair

**Comment by bsoufflet** [comment]
Done.
- t_type magazine supprimé
- migration de tous les t_document magazine vers collection
- suppression des relation j_licence_type avec des magazines
