### ISSUE TITLE
[DOC] Subjects mismatching

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#467]
Christoph m'indique que lorsqu'il attribue le code 2.11 à un document, dans la fiche récapitulative c'est le code 2.22 qui apparait.
Il est alors obligé de reprendre la fiche pour mettre le bon code qui est alors bien pris en compte

**Comment by Clm-Roig** [comment]
Chez moi ça marche correctement. J'ai soumis un 2.11 et j'ai obtenu un 2.11 lors de la validation côté admin.

**Comment by urien** [comment]
En ligne c'est bon aussi.
Je n'ai pas eu de pb
