### ISSUE TITLE
[DOC] URL identifier type issue

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#469]
Quand je mets l'url d'un document et que j'indique que c'est une url, le formulaire n'est pas conten, il accepte ce que je mets si je lui indique que c'est un DOI
![image](https://user-images.githubusercontent.com/1165144/103414361-ecc10500-4b7d-11eb-99fc-8aa61a82a24a.png)

**Comment by Clm-Roig** [comment]
Problème connu que j'avais réglé à la main. Il faut intervenir sur le regex en base de données. 

Je le règle encore une fois à la main et je le change sur le dump de données sur le repo privé qui contient les données de la v2.

**Comment by Clm-Roig** [comment]
C'est corrigé, je ferme !
