### ISSUE TITLE
Add Romanian language

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#475]
Est ce qu'il serait possible de rajouter le Roumain aux langues disponibles et de pousser une nouvelle version de GC V3 pour rendre cette nouvelle langue disponible ?

**Comment by bsoufflet** [comment]
v3.4.12

**Comment by bsoufflet** [comment]
J'ai rajouté "ro" dans la liste et fait un deploy mais rien ne s'est traduit... Une idée @urien ?

**Comment by urien** [comment]
Pour te répondre je suis allé voir et c'est bon !
Merci

**Comment by urien** [comment]
Heu, non, la langue apparait maintenant dans la liste mais ce n'est pas le Roumain qui apparait

**Comment by bsoufflet** [comment]
Oui c'est ca le problème... Comment le matching est fait avec transifex ? Via le code langue "ro" ? Faut il faire quelque chose coté Transifex ?

**Comment by urien** [comment]
J'avais l'impression que dans le processus de mise à jour, les fichiers étaient récupérés sur Transifex. Peut être que dans le script il faut préciser les langues qui doivent être récupérées ?

**Comment by bsoufflet** [comment]
Done ! On a un petit problème dans notre processus de deploy en prod. On ne fait jamais la tache Grunt "buildProd" qui contient la sous tache de téléchargement des fichiers de lang de transifex...
Je viens de les lancer manuellement et du coup toutes les langues sont à jour !

**Comment by Clm-Roig** [comment]
J'ai toujours fait la mise à jour des traductions manuellement, via la commande `grunt transifex` sur ma machine puis en commitant les changements sur le repo 🙂 C'est top si maintenant c'est automatique pour la mise en prod !
