### ISSUE TITLE
I can't add an author

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#476]
Quand je souhaite choisir un auteur il y a 2 propositions qui correspondent à mon souhait

![1](https://user-images.githubusercontent.com/1165144/104739160-b28f6000-5746-11eb-9652-38e398ee941c.png)

Mais quand j'en choisi un il apparait comme indéfini
![Capture d’écran 2021-01-15 152633](https://user-images.githubusercontent.com/1165144/104738818-4c0a4200-5746-11eb-9079-efc49dfd1181.png)
J'ai essayé de le recréé mais ce n'est pas possible

**Comment by Clm-Roig** [comment]
>  J'ai essayé de le recréé mais ce n'est pas possible
C'est-à-dire ? Quelle est l'erreur renvoyée ?

**Comment by urien** [comment]
Quand je sélectionne Laurent Hermand ou Hermand laurent dans la liste j’obtiens "undefined" comme auteur. (voir la seconde image)
Quand on souhaite créer Laurent Hermand comme un nouvel auteur le bouton pour valider est inactif. C'est normal qu'on ne puisse pas créer un auteur qui existe déjà, peut être faudrait-il un message pour expliquer pourquoi on ne peut créer cet auteur.

**Comment by Clm-Roig** [comment]
> Quand on souhaite créer Laurent Hermand comme un nouvel auteur le bouton pour valider est inactif. C'est normal qu'on ne puisse pas créer un auteur qui existe déjà, peut être faudrait-il un message pour expliquer pourquoi on ne peut créer cet auteur.

Il n'y aucun contrôle du fait que l'auteur existe ou pas déjà dans la base de données, je viens de vérifier. 

Je vais voir pour le reste !

**Comment by Clm-Roig** [comment]
Le fait qu'il y ait écrit "undefined" vient du fait que ce caver-là n'a pas de **name** et/ou de **surname** : il a uniquement un pseudo. Or, pour l'affichage, on affiche **surname name**, d'où le undefined vu qu'il n'en a pas.

**Comment by Clm-Roig** [comment]
Je vais fusionner les 2 entrées dans la BD pour cet auteur, c'est en cours.

**Comment by urien** [comment]
Merci,
Le problème qu'on avait c'est que la création d'un nouvel auteur était inactive. Le clic sur le bouton ne produisait rien.

**Comment by Clm-Roig** [comment]
>  Le problème qu'on avait c'est que la création d'un nouvel auteur était inactive. Le clic sur le bouton ne produisait rien.

J'ai pas de souci chez moi avec ça. Tu t'es déconnecté / reconnecté avant histoire d'être sûr que ton authentification est valide ?

**Comment by urien** [comment]
Tu as raison, c'est cela. Je ferme cette issue
