### ISSUE TITLE
[ADV SEARCH] Missing depth and length in result table for entries

### ISSUE THREAD

**Issue by bsoufflet** [GrottoCenter/Grottocenter3#479]
For the single entries the depth and length is not displayed in the result table: 
![image](https://user-images.githubusercontent.com/985903/105465920-d812f100-5c93-11eb-8397-0d827f8f834b.png)
But these entries really have depth and length:
![image](https://user-images.githubusercontent.com/985903/105465975-eb25c100-5c93-11eb-9843-3368994b7f0b.png)

**Comment by Clm-Roig** [comment]
J'ai trouvé le souci, c'est dans **logstash.conf**, lorsque l'on fait la jointure entre l'entrée, sa cavité et son massif : 

```sql
LEFT JOIN (
        SELECT 
          c.id AS id_cave, c.depth AS depth_cave, c.length AS length_cave, c.is_diving AS is_diving_cave,
          n1.name AS name_cave, n2.name AS name_massif
        FROM t_cave c
        LEFT JOIN t_name n1 ON n1.id_cave = c.id
        LEFT JOIN t_massif m ON m.id = c.id_massif
        LEFT JOIN t_name n2 ON n2.id_massif = m.id
        WHERE n1.is_main = true # <---- PROBLEME ici
        AND n2.is_main = true # <---- PROLEME ici
      ) cave_and_massif ON cave_and_massif.id_cave = e.id_cave
```

Si la cavité (ou le massif) dans laquelle se situe l'entrée n'a pas de "main name", on ne retourne pas la cavité... et donc sa profondeur / longueur.

**Comment by Clm-Roig** [comment]
Je viens de regarder un peu cette issue. On a actuellement 59 646 caves sur 60 113 qui n'ont pas de noms. 

Sur ces 59k cavités, est-ce qu'il ne serait pas pertinent de leur attribuer un nom (via une requête SQL) selon les conditions suivantes : 
- la cavité n'a qu'une entrée
- cette entrée a un main_name
- on copie ce main_name et on l'associe à la cavité

Qu'en pensez-vous ? ça va dupliquer pas mal de données mais en même temps notre modèle est conçu pour gérer plusieurs noms par entrée ET plusieurs noms par cavité : ce serait plus cohérent :slightly_smiling_face:

**Comment by Clm-Roig** [comment]
@bsoufflet je pense que ce problème peut désormais être résolu facilement ! Tu as fait en sorte de nommer toutes les caves de Grottocenter. 
On pourrait exécuter  une dernière requête qui, pour tous les names, s'il n'y en a qu'un, change "is_main" à true ?

**Comment by bsoufflet** [comment]
Ok, je peux m'en occuper :)

**Comment by bsoufflet** [comment]
@Clm-Roig : La totalité des `t_name` ont actuellement `is_main = true` en BDD donc le problème ne vient pas de là...
Il y avait beaucoup de cave associées à un massif avec l'ID 0. J'ai donc ajouté une ligne dans t_name pour ce massif 0 avec is_main = true
Faut il maintenant lancer un logstash pour voir si ca fonctionne ?

**Comment by Clm-Roig** [comment]
Il suffit d'attendre une heure pour que Logstash soit relancé. Si ça fonctionne pas, je regarderai pourquoi.

**Comment by bsoufflet** [comment]
C'est bon :)
![image](https://user-images.githubusercontent.com/985903/165702441-8fa3a641-f945-4c43-8628-5039b7116e0c.png)
