### ISSUE TITLE
Add GScan Partner

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#484]
Voici le logo

[logo_gscan.zip](https://github.com/GrottoCenter/Grottocenter3/files/5909388/logo_gscan.zip)

**Comment by Clm-Roig** [comment]
C'est quoi le nom complet à afficher pour ce partenaire ? J'imagine que GScan c'est un acronyme, on a l'habitude de mettre le nom entier dans Grottocenter.
