### ISSUE TITLE
[DB] NOT NULL value for Entrance Name

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#489]
Actuellement il est possible d'avoir en base de données des cavités sans nom, il faudrait fixer la valeur name pour les entrances à NOT NULL

**Comment by Clm-Roig** [comment]
Le souci c'est que si on fait ça, quel nom on attribut à toutes les cavités qui n'ont pas de nom ? (il y en a dans la BD il me semble non ?)

**Comment by urien** [comment]
On peut mettre "unnamed cave"

**Comment by Clm-Roig** [comment]
Je viens de regarder, on a que 6 entrées sans nom : ça vaut peut-être le coup de retrouver ces noms ou bien de supprimer ces entrées. Puis après on met la condition de non-nullité sur toute la table.

![image](https://user-images.githubusercontent.com/20704943/107398912-65fa3300-6b00-11eb-9109-21808ba373ba.png)

74493
74494
74495
74496
74497
74498

**Comment by urien** [comment]
Je regarde sur la V2

**Comment by urien** [comment]
Ce sont des cavités avec comme coordonnées 0,0 il faut les supprimer
on dirait des cavités rajoutées via une requête sql sans passer par l'application

**Comment by Clm-Roig** [comment]
Ok je m'en occupe

**Comment by Clm-Roig** [comment]
J'ai supprimé les 6 entrées dont on parlait. 
Cependant, concernant les 3 cavités qui n'ont pas de nom (74497, 74498 et 75260) : 
- deux (la 74497 et la 75260) n'ont pas d'entrées => je supprime.
- une (la 75260) a des entrées avec des noms et situées en Corrèze (cf screen). 

![image](https://user-images.githubusercontent.com/20704943/107401479-36005f00-6b03-11eb-8b39-6380da5e54c4.png)

Il doit y avoir moyen de retrouver son nom j'imagine.

**Comment by WillyKaze** [comment]
A partir des liens suivants, la 75260 seraient nommée `Réseau de la Couze`:
- http://speleo-correze.org/cavites/briant/briant_description.htm
- http://speleo-correze.org/cavites/jonquilles/jonquill.htm

**Comment by urien** [comment]
Merci, au niveau applicatif je n'arrive pas à faire la mise à jour.
Benoit est ce que tu souhaiterais échanger directement avec les développeurs sur Slack ?
https://grottocenter.slack.com

**Comment by Clm-Roig** [comment]
Je peux faire cette mise à jour, je m'en occupe rapidement

**Comment by Clm-Roig** [comment]
La cavité est bien renommée, merci ! :slightly_smiling_face: On n'a plus aucune entrée sans nom désormais. 

Concernant la contrainte de non-nullité sur le nom, je n'ai pas les compétences pour l'implémenter sur la base de données : il faudrait un trigger. Par contre, je vais consolider la route de l'api qui permet de créer une entrée de cavité pour qu'elle teste la présence d'un nom. 

ça te paraît suffisant @urien ?

**Comment by WillyKaze** [comment]
> Merci, au niveau applicatif je n'arrive pas à faire la mise à jour.
> Benoit est ce que tu souhaiterais échanger directement avec les développeurs sur Slack ?
> https://grottocenter.slack.com

Oui si possible, je n'ai par contre pas réussi à rejoindre le slack de grottocenter, je pense qu'il me faut un lien d'invitation.

**Comment by urien** [comment]
Pour l'installation de Grottocenter tu pourra solliciter les développeurs.
Peux tu me faire suivre ton mal à president@grottocenter.org pour que je te fasse passer une invitation ?

**Comment by Clm-Roig** [comment]
Je ferme car : 
- toutes les entrées ont désormais un nom
- la création d'une entrée nécessite forcément un nom côté serveur

(même chose pour les caves d'ailleurs)
