### ISSUE TITLE
Connection problem on V3

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#492]
Aude Vial m'indique qu'elle a un message "erreur serveur" lorsqu'elle essaye de se connecter sur la V3.

Quand on regarde son compte, en fait il y en a 3 avec le même mel... Et je pense que pour Aude il n'y en a qu'un parmi les 3 qui est le bon
![Aude](https://user-images.githubusercontent.com/1165144/107468429-34b54d80-6b68-11eb-9693-519fa0ae45f4.png)

**Comment by urien** [comment]
Aude utilise le compte avec audelucievial comme login

**Comment by Clm-Roig** [comment]
C'est bon c'est réglé, j'ai supprimé les comptes dupliqués. A noter que ce problème va se reproduire pour d'autres comptes : 
[duplicated_mails.pdf](https://github.com/GrottoCenter/Grottocenter3/files/5957281/duplicated_mails.pdf)

**Comment by Clm-Roig** [comment]
Je ferme, n'hésite pas à ré-ouvrir si y a toujours un problème @urien
