### ISSUE TITLE
[DOC VALIDATION] Missing validator id

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#497]
When someone validate a document, his id is not written in the database, in the id_validator field.

See **DocumentController.js** validate() and multipleValidate() methods.

**Comment by Clm-Roig** [comment]
Also, what's the difference between **validator** and **reviewer** ?

**Comment by Clm-Roig** [comment]
> Also, what's the difference between **validator** and **reviewer** ?

@urien une idée de cette différence dans la base de données ? :slightly_smiling_face:

**Comment by urien** [comment]
Je pense que reviewer c'est la dernière personne ayant fait des modifications. Avec lnhistorisation on saura quelles sont les contributions de chacun.
Validation ne doit exister que pour les docs. C'est celui qui a accepté ou refusé la publication du document

**Comment by Clm-Roig** [comment]
Ok donc ici je dois mettre l'id dans validator donc, merci 🙂
