### ISSUE TITLE
[DB] Cleanup of cavers table

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#498]
Sur la V2 il était possible de créer une multitude de comptes avec le même mail ce qui n'est pas possible sur la V3 et génère des dysfonctionnement

Il pourrait être intéressant, quand les mots de passes pourront être récupérés, de nettoyer la base  pour ne garder qu'un compte par mel, les contributions des comptes supprimés devant être attribuées au compte conservé

**Comment by urien** [comment]
Pour mes comptes il faudrait conserver les comptes avec des noms et prénoms différents du mien et leur mettre no mail comme mail.

**Comment by Clm-Roig** [comment]
> Pour mes comptes il faudrait conserver les comptes avec des noms et prénoms différents du mien et leur mettre no mail comme mail.

J'ai nettoyé tout ce qui concernait tes comptes, c'est bon :slightly_smiling_face:

**Comment by bsoufflet** [comment]
@urien @Clm-Roig : On considère que cette issue est done ?

**Comment by urien** [comment]
Je vais demander à Didier s'il a pu récupérer son mon de passe

**Comment by urien** [comment]
C'est bon, cela fonctionne, tu peux clore ce ticket.

Merci

**Comment by bsoufflet** [comment]
New unique constraint on email added to the DB :)
