### ISSUE TITLE
Center the map when you access it

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#50]
Actuellement j'arrive sur le sud de l'Angleterre, il faudrait soit centrer sur la position de l'utilisateur, soit si sa position est inconnue afficher la terre entière

![screenshot-localhost 8081-2018-03-21-20-17-25](https://user-images.githubusercontent.com/1165144/37732522-8c7ddee2-2d45-11e8-99b4-aed32475a480.png)

**Comment by urien** [comment]
En fait la position est bonne si on active la localisation. Il suffit donc d'afficher la terre entière quand la localisation n'est pas activée

**Comment by Kurdty** [comment]
Pour afficher la terre entière, pas de soucis, suffit que je mette le bon niveau de zoom.
Par contre je suis contraint de choisir une position. Je peux prendre (0,0) au lieu de Londres.
https://www.thoughtco.com/prime-meridian-and-the-equator-intersect-4070819

Qu'en penses-tu ?

**Comment by urien** [comment]
Oui, c'est plus central....
