### ISSUE TITLE
Footer icons homogenization / replacement

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#52]
Je propose que les pictos dans le footer soient les meme que pour la page d'accueil et que les liens textes soient remplacés par des pictos

**Comment by Kurdty** [comment]
Hi @ClemRz 
If you want to try to code on GC3, here is a simple issue, well designed to discover our front-end :)

**Comment by Clm-Roig** [comment]
It's done, I'm closing.
