### ISSUE TITLE
To add in menu

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#53]
La structure sera la même pour les entrées, les groupes et les spéléos. Il faudra sans doute donner accés aux réseaux et aux massifs avec des pages spécifiques. il faudra également prévoir un menu pour acceder au module de conversion

**Comment by Kurdty** [comment]
I think that each section on website will have to be initiated on it's own issue.
I set the issue to "splittable" :)

**Comment by Clm-Roig** [comment]
A lots of things have been done concerning this one since it was created. I'm closing but we can open new issue more specific if needed (as Kurdty explained it) :slightly_smiling_face: .
