### ISSUE TITLE
[DOCUMENTS] Allow users to see their contributions

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#538]
# Issue
Currently, an user can't see its contribution to the Grottocenter's document database.

# Proposal
On the page **https://beta.grottocenter.org/ui**, add a tile "**My contributions**". When clicked, it will display a page listing all the user document contributions. Later, we will add the cave, massif and organization contributions on this page for example.
![image](https://user-images.githubusercontent.com/20704943/114937153-b57d1800-9e3d-11eb-8733-6611aa794c8f.png)

What is needed: 
- API route (**GET /users/{userId}/documents**)
- Add a "My contributions" tile on dashboard
- Add a component / feature **Contributions.jsx**

**Comment by ClemRz** [comment]
Starting on this.

**Comment by ClemRz** [comment]
For the sake of consistency in our models, wouldn't it be better if the API route was `/cavers/{userId}/documents` ?

**Comment by Clm-Roig** [comment]
Fixed by #583, I'm closing
