### ISSUE TITLE
Users can't create an autor in a BBS form

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#547]
Ce problème avait été déjà indiqué et il est encore apparu aujourd'hui. Un utilisateur connecté avec une session qui vient juste d'être créé saisi le nom d'un auteur, comme il est absent de la liste il clique sur le + indique son nom et son prénom le bouton créer devient orange et quand il clique dessus rien ne se passe.
Il utilise firefox sous windows comme moi et pour moi cela fonctionne.
Christophe Bes qui m'avait indiqué ce problème a refait un essai aujourd'hui et il n'arrive pas, lui non plus, à créer un nouvel auteur

**Comment by Clm-Roig** [comment]
Je m'en occupe cet aprem, simple souci de base de données de production.

**Comment by Clm-Roig** [comment]
Fixed by #552 
Je fais un déploiement d'une nouvelle version dans la foulée.
