### ISSUE TITLE
[DOCUMENT] BBS Code

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#549]
Le code BBS 2.22 devrait être associé ) l'Amérique du sud et pas à Europe occidentale (qui est déjà le 2.11 de mémoire)

**Comment by Clm-Roig** [comment]
Je n'ai pas trop bien compris le problème, j'ai ça actuellement dans la base de données de production : 
![image](https://user-images.githubusercontent.com/20704943/115881579-2cbd3800-a44c-11eb-9b9f-590e0b3d04df.png)

Est-ce que tu peux me préciser, en séparant clairement : 
- le comportement actuel problématique de l'application
- ce qu'il faudrait qu'il y ait comme solution

**Comment by urien** [comment]
A l'affichage on a le même intitulé pour 2.11 et 2.22. C'était une erreur sur Transifex que j'ai corrigée
![image](https://user-images.githubusercontent.com/1165144/115892331-56c82780-a457-11eb-9bd8-a5a6948cd623.png)
