### ISSUE TITLE
Move the map when a bubble is open

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#56]
Actuellement lorsqu'on déplace la carte alors qu'une info-bulle est ouverte il y a un bug d'affichage (cela bouge tout seul) puis un ralentissement et un plantage

**Comment by Kurdty** [comment]
J'ai pu reproduire le bug.
Il y a un bouclant (un événement qui provoque un refresh, qui provoque un événement, qui provoque un refresh, ...)
Je vais faire l'analyse
