### ISSUE TITLE
[Account] Problème de création de compte

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#582]
Bonjour,

Une correspondante n'arrive pas à créer de compte quand elle complète le formulaire, la roue tourne mais rien ne se passe

----------------
the email address I used was mce4@sfu.ca (this one), when I fill in all the fields, nothing happens - the sign in button just spins, then returns to 'sign in'.

Should I try a different email address?

**Comment by Clm-Roig** [comment]
Apparemment ça plante quelles que soient les informations saisies.

**Comment by Clm-Roig** [comment]
J'ai trouvé le souci, il s'agit d'une mauvaise utilisation de ma part du helper **CheckIfExists**. D'autres fonctionnalités ont dû sauter aussi je pense : je corrige ça.

**Comment by Clm-Roig** [comment]
Fixé par #3ec01f 
Je déploie dans la foulée.
