### ISSUE TITLE
Add Flow to the project ?

### ISSUE THREAD

**Issue by Kurdty** [GrottoCenter/Grottocenter3#59]
See https://flow.org

Flow is used to enhance code quality by checking JS types dynamically.

On server side, it could be very interesting.
On React side we already have a mecanism of props checking, so we have to determine if it is necessary or not.

So analyse is necessary.

**Comment by bsoufflet** [comment]
@maximenathan : Et ca tu en penses quoi ?

**Comment by maximenathan** [comment]
Typescript ce serait bien. Flow n'est plus bien maintenu
