### ISSUE TITLE
[DOC EDITION] Bug on moderator edition for a new document

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#607]
Quand en tant que modérateur je souhaite éditer un document j'ai un message d'erreur
![image](https://user-images.githubusercontent.com/1165144/130046519-2cabb761-495b-430c-8aa2-f5d8dbd48693.png)

**Comment by urien** [comment]
Message : Une erreur serveur s'est produite - Fetching document id 130174

**Comment by AxelCanton** [comment]
En effet j'ai oublié quelque chose d'important...
#608
