### ISSUE TITLE
[LANGUAGES] List too short

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#609]
Quand on travaille sur un document
On ne peux choisir une langue que parmi celles qui sont proposées par Grottocenter. Et naturellement nous allons décrire des documents dans toutes les langues et les contributeurs vont s'exprimer dans leur langue qui peut ne pas figurer dans cette ligne.
Il faudrait donc proposer une liste complète des langues existantes
![image](https://user-images.githubusercontent.com/1165144/130311366-2dba51ae-ebdc-4d3c-93fc-48bbedad86fc.png)

**Comment by Clm-Roig** [comment]
Fixed by PR #766
Duplicate of Issue #723
