### ISSUE TITLE
[ORGANIZATION SEARCH] Undefined name

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#610]
Quand je choisi une organisation dans la liste (pour définir l'éditeur) certaines organisation apparaissentndifféremment
![image](https://user-images.githubusercontent.com/1165144/130344574-c7f4e5b6-43a2-4f31-b6fd-32fcfc181fd5.png)
Sur l'image c'est le cas de la société quebecoise de spéléo
si je la sélectionne alors elle apparait comme "undefined". J'ai l'impression qu'il manque quelque chose en base de données pour certaines organisations

**Comment by urien** [comment]
l'image avec la société quebecoise de spéléo qui a été selectionnée
![image](https://user-images.githubusercontent.com/1165144/130344651-838008ae-71bf-4e3e-a8e2-472796550b10.png)

**Comment by Clm-Roig** [comment]
Son nom ne s'affiche pas car elle n'a pas de "main_name" dans la base de données. Je propose d'exécuter une requête sur la BD de prod sur toutes les organisations avec un seul name qui permet de désigner comme main_name leur seul name.

**Comment by urien** [comment]
Oui ce serait parfait

**Comment by Clm-Roig** [comment]
La requête SQL a bien été exécutée sur la BD. J'ai relancé logstash pour mettre elasticsearch à jour mais ça n'a rien changé j'ai l'impression... 
@bsoufflet tu pourras regarder à l'occasion ?
