### ISSUE TITLE
[TESTS] Run tests using a mock database

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#634]
See my comment here : https://github.com/GrottoCenter/Grottocenter3/pull/629#issuecomment-943298608

**Transaction and native query can't be tested using sails-disk**

> ## Souci avec sails-disk 
> 
> Désormais j'ai un autre gros souci. Pour les tests on utilise `sails-disk` qui permet d'utiliser une BD légère stockée sur le disque. Dans nos contrôleurs on utilise les "transactions" pour pouvoir annuler une création complexe de données quand une partie échoue (par exemple, on ne créé un document que si on arrive à créer son nom dans la table des noms). 
> 
> Or `sails-disk` ne supporte pas les transactions... Je suis donc bloqué pour le moment. 
> 
> **Chose assez intrigante** 
> 
> En local, quand je stoppe mon container de la BD, j'ai effectivement des erreurs sur le test qui utilise les transactions (création de documents). 
> Mais quand je relance la BD puis les test, que je compte mes documents de test (3 au total), que je créé 2 documents (ok), puis que je fais un test sur le nombre de documents dans la BD de test, j'ai bien le nombre attendu dans les tests (5 = 3 de base + 2 créés)... alors que dans ma BD locale j'en ai bien plus ! 
> 
> **Conclusion (étrange) 🤔  :** Sails / Mocha a bien besoin de la connexion à la BD PostGre mais ne l'utilise pas pour créer des données vu qu'il se base sur la BD de test du disque... ?!
> 
> ### Solution (temporaire)
> 
> On ne teste pas les fonctions qui utilisent les transactions. A terme, on se débrouille pour avoir une BD de test PostGre qui est créée à la volée et ainsi tester dans des conditions aussi proches que possible de la prod.

## TODO

- Add a docker container **postgresgrotto_test** to docker-compose.yml.
- Populate it with fake data (same as postgregrotto dev DB).
- Modify `datastores.js` test database connection.
- Perform tests & coverage.

A new Github action `test` must be created and will do the same things (currently, the github "test" part is done in the **build** action).

**Comment by Clm-Roig** [comment]
Une autre solution envisageable : réussir à wrapper l'outil de transaction de Sails dans un outil à nous. Celui-ci aurait un comportement différent selon si on est en test ou en prod / dev : 
- test => pas de transaction
- dev / prod => transaction

**Comment by bsoufflet** [comment]
On est déjà bien dans du test d'intégration et ca devient en effet tout de suite compliqué car il faut un environnement de test... Comme tu le dis avoir un BD postgre juste pour le test serait l'idéal... On pourrait le faire pour peut etre pas grand chose sur Azure mais j;imagine que c'est pas la 1ere priorité en ce moment ;)

**Comment by Clm-Roig** [comment]
J'hésite quand même à développer le petit wrapper que j'ai mentionné : ça permettrait de tester quasiment tout et de gagner en sérénité quand on touche à quelque chose (cf mon expérience perso où j'ai toujours peur de toucher aux fonctionnalités de création / update vu leur complexité) :sweat_smile:
