### ISSUE TITLE
[DOC] Getting all child documents is taking too much time

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#644]
The largest Grottocenter collection has 1000 child documents. It doesn't load on the client because the server is taking way too much time to complete the request. Even with 100 child documents it can take around 10s. 

## Solution proposal

Send the documents without its children, ask them in another request. The children request can take a lot of time too, maybe it will be necessary to make it partial with some _**from**_ and _**size**_ parameters (ex: load the 0-20 children, then 20-40 etc.)

**Comment by Clm-Roig** [comment]
@urien @bsoufflet suite à notre conversation autour des document enfants qui mettent trop longtemps à se charger :wink:

**Comment by urien** [comment]
Pourquoi pas, mais l'ordre sera celui des id et pas celui des numéros. Pour les utilisateurs il va être difficile de savoir si un enfant existe ou pas, et à quelle page il va apparaitre
Est ce qu'il n'y aurait pas une solution côté base de données en créant des tables dédiées qui retourneraient plus rapidement les résultats ?

**Comment by Clm-Roig** [comment]
Ok pour le tri par id, c'est facile à réaliser.

Le chargement 20 par 20 peut être géré automatiquement, sans intervention de l'utilisateur. Il voit que les documents sont en train d'arriver, il regarde ceux déjà chargés et pendant ce temps on en charge d'autres petit à petit. Il n'aura pas le temps de vérifier les 20 premiers que déjà 20 supplémentaires seront chargés j'imagine. 

Qu'en penses-tu ? 

Sinon côté serveur / BD, faudrait que je fasse des tests pour voir si je trouve une solution mais là je vois pas.

**Comment by urien** [comment]
Je me suis mal exprimé, le tri par id serait un pb. L'idéal c'est le tri par ordre alphabétique et si le chargement est transparent pour l'utilisateur c'est une solution parfaite

**Comment by Clm-Roig** [comment]
Ok ça marche, je vais travailler à ça.

**Comment by bsoufflet** [comment]
C'est quoi la requête SQL actuellement pour récupérer les enfants ? Ce
n'est pas juste un problème d'index qui manque ou qui est mal fait ?

Le sam. 30 oct. 2021 à 22:18, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
Il y a un premier `populate("children"` effectué par Sails pour récupérer les ids et les données de "base" des documents enfants. Puis après j'itère dessus pour compléter ces données avec leur description qui contient le nom du document. 

L'itération pour la description est longue mais le premier `populate("children")` l'est également. Il faut que je passe du temps à tester tout ça pour y voir plus clair. 

(Semi HS : de manière générale, le système de jointure de Sails, le populate() donc, est vraiment pas top et ils l'ont jamais fixé... Et les packages tiers qui corrigent ça et que j'ai testé ne fonctionne pas toujours.)

**Comment by Clm-Roig** [comment]
J'ai repris tout le code qu'effectuait Sails automatiquement pour le faire à la main histoire d'optimiser la requête. 

Pour la collection avec le plus d'enfants (**1072** au total), j'ai un temps de chargement de **11 secondes** (pour 500 enfants ça tombe à **6 secondes**, ça a l'air relativement linéaire). Le plus gros temps d'exécution c'est de récupérer tous les enfants avec leur description peuplée. J'ai réussi à le faire en une seule commande (avant j'itérais sur chaque child id et donc y avait 1000 requête à envoyer) mais ça traîne quand même sur 7-8 secondes : 

```js
const children = await TDocument.find({ id: { in: childIds } }).populate(
  'descriptions',
);
```

J'envisage donc de récupérer les enfants, soit page par page, soit tout d'un coup, dans tous les cas ce sera fait en parallèle, de manière qu'on puisse afficher tout le reste du document pendant que ça charge.

**Comment by urien** [comment]
Je ne sais pas si cela change quelque chose, mais est ce que tu ne pourrais récupérer que l'id et le nom des enfants ?

**Comment by Clm-Roig** [comment]
Pour les documents, description = nom pour résumer justement ^^

**Comment by bsoufflet** [comment]
Un chargement au fur et à mesure me semble pas mal pour avoir de la
réactivité. Par exemple tu récupères juste la liste des IDs des enfants que
tu renvoies au front puis le front va demander au fur et à mesure la liste
des enfants et faire grossir la liste en montrant que le chargement est en
cours mais en laissant l'utilisateur utiliser la page.

Le lun. 1 nov. 2021 à 20:19, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
Je vais faire ça oui !
