### ISSUE TITLE
[DB] Cleanup the table with the list of accepted file formats

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#655]
Actuellement cette table contient une liste exhaustive de format, cela ralentit le traitement et certains formats ne sont pas pertinent.

Je propose de

- supprimer tous les types pour lesquels il n'y a pas d'extension
- de conserver les extensions habituelles pour les textes, les tableaux, les présentations, les images, les sons, les vidéos, les fichiers compressés ainsi que le pdf
- de conserver (ajouter ?) les fichiers correspondant à des points topo : gpx, kml, kmz, top, tro, dat, json, osm, dxf, pos, 3d, svx, plt, xvi, loch, dxf, trox, plt, shp

Une autre approche plus rapide serait de supprimer les lignes sans extension et les lignes correspondant des types de fichier qu'on estime ne jamais devoir servir

**Comment by Clm-Roig** [comment]
> 
> Je propose de
> 
>     * supprimer tous les types pour lesquels il n'y a pas d'extension

Faisable en 1 minute, j'ai rien contre. Dès que j'ai ton aval, je peux m'en charger. Je viens de regarder : ça concerne xxx types sur xxx.

>     * de conserver les extensions habituelles pour les textes, les tableaux, les présentations, les images, les sons, les vidéos, les fichiers compressés ainsi que le pdf

Pourquoi pas, ça prendra un peu plus de temps.

>     * de conserver (ajouter ?) les fichiers correspondant à des points topo : gpx, kml, kmz, top, tro, dat, json, osm, dxf, pos, 3d, svx, plt, xvi, loch, dxf, trox, plt, shp
> 

J'éditerai ce message pour lister les formats déjà présents et/ou absents :

gpx
kml
kmz
top
tro
dat
json
osm
dxf
pos
3d
svx
plt
xvi
loch
dxf
trox
plt
shp

**Comment by urien** [comment]
Oui merci de supprimer les lignes sans extension
J'ai demandé à Benjamin s'il pouvait prendre en charge cette issue, ce
serait bien qu'il y ai un autre regard sur les extensions utiles

Le jeu. 18 nov. 2021 à 16:05, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
> 
> Je propose de
> 
>     * supprimer tous les types pour lesquels il n'y a pas d'extension

Faisable en 1 minute, j'ai rien contre. Dès que j'ai ton aval, je peux m'en charger. Je viens de regarder : ça concerne 374 formats sur 969.

>     * de conserver les extensions habituelles pour les textes, les tableaux, les présentations, les images, les sons, les vidéos, les fichiers compressés ainsi que le pdf

Pourquoi pas, ça prendra un peu plus de temps.

>     * de conserver (ajouter ?) les fichiers correspondant à des points topo : gpx, kml, kmz, top, tro, dat, json, osm, dxf, pos, 3d, svx, plt, xvi, loch, dxf, trox, plt, shp
> 

J'éditerai ce message pour lister les formats déjà présents et/ou absents :

gpx
kml
kmz
top
tro
dat
json
osm
dxf
pos
3d
svx
plt
xvi
loch
dxf
trox
plt
shp

**Comment by bsoufflet** [comment]
@urien Je ne suis pas un grand connaisseur de tous les formats de fichier pour les fichiers topo (therion, topodroid, ... Il faudrait peut etre demander à  Domi qui a fait un stage topo récemment il me semble...
Il semble y avoir un paquet de logiciels donc potentiellement un paquet de types de fichiers ? Mais il est peut etre préférable de ne pas supporter des formats trop exotiques qui demanderaient d'installer un logiciel particulier pour relire le fichier et plutot se concentrer sur quelques formats plus standard ou plus open ?

Au pire on pourra toujours ajouter les manquants à la demande...

En SIG les nouveaux standards (en plus du shp) sont plutot : 
- geopackage -> gpkg
- geojson

**Comment by urien** [comment]
J'ai mis à jour la liste établie par Clément avec les propositions de Benjamin et de Dominique

**Comment by Clm-Roig** [comment]
Que manque-t-il pour fermer cette issue ? Ci-joint la liste des extensions déjà présentes en prod :
[_select_id_name_surname_nickname_mail_from_t_caver_where_mail_no_202112071534.txt](https://github.com/GrottoCenter/Grottocenter3/files/7740633/_select_id_name_surname_nickname_mail_from_t_caver_where_mail_no_202112071534.txt)

**Comment by urien** [comment]
Il y a plein d'extension qu'il faut enlever. Comment je peux te faire passer la liste des extensions à conserver ? Je mets à jour le fichier json ?

**Comment by Clm-Roig** [comment]
Le plus simple c'est de me dire quoi supprimer, en me donnant une liste d'ids ou d'extensions. Je me débrouille après pour mettre ça en forme pour une requête SQL :slightly_smiling_face:

**Comment by urien** [comment]
ok
Voila le fichier. Certaines extensions apparaissent deux fois j'ai laissé les doublons dans le fichier
[extensions à supprimer.txt](https://github.com/GrottoCenter/Grottocenter3/files/7740676/extensions.a.supprimer.txt)

**Comment by Clm-Roig** [comment]
J'ai effectué la suppression. Cependant, certains fichiers utilisent actuellement les extensions suivantes (je n'ai donc pas pu les supprimer) : tiff, bmp, dpt, trk

tiff et bmp sont rares mais toujours bien présents pour les images. 
dpt et trk je ne connais pas du tout par contre.

**Comment by urien** [comment]
Merci Clément,
C'est parfait ainsi.
