### ISSUE TITLE
[CSV] problem with identifier

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#656]
Quand je fais un import csv si je mets URL comme identifier type j'ai une erreur, par contre l'import se déroule normalement si je ne mets rien.

**Comment by Clm-Roig** [comment]
@urien Il me faudrait le .csv que tu utilises à chaque fois que tu ouvres une issue s'il te plaît. Des fois le problème est plus complexe qu'il n'en a l'air et je ne peux pas le reproduire juste en faisant ce que tu indiques.

**Comment by Clm-Roig** [comment]
Du nouveau là-dessus ?

**Comment by urien** [comment]
C'est réglé
