### ISSUE TITLE
[CSV Download Files] Should not crash when the file download / upload fails

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#660]
Lorsque je souhaite télécharger le fichier suivant j'ai une erreur à la dernière étape

--------
Exception: `distantFileDownload` failed ("formatRefused").  The file format is in the refusedFileFormats list.
Additional data:

'html'
-----------
Alors que c'est un fichier csv qui est déclaré
[OREME.csv](https://github.com/GrottoCenter/Grottocenter3/files/7589839/OREME.csv)

**Comment by Clm-Roig** [comment]
L'url indiquée dans dct:source retourne une page HTML (une page 404 pour être précis). 
Donc on se retrouve à télécharger un fichier dans un format que l'on ne souhaite pas (HTML). 

Question qui en découle : lorsque le téléchargement échoue, ça ne devrait pas planter non ? Juste indiquer que ça a raté mais quand même créer le document ?

**Comment by urien** [comment]
Oui, mais là l'URL pointe vers un csv.
Il y a un // dans l'adresse, peut être que l'adresse n'est pas lue jusqu'au
bout.

Le mar. 23 nov. 2021 à 22:23, Clément Roig ***@***.***> a
écrit :

**Comment by Clm-Roig** [comment]
Chez moi l'url pointe vers une 404, qu'importe qu'il y est écrit ".csv" dedans : le lien n'est pas (plus ?) valide.

**Comment by urien** [comment]
Ok, du coup il faut renommer l'issue : le doc aurait dû se créer sans
importer de fichier

Le mar. 23 nov. 2021 à 22:32, Clément Roig ***@***.***> a
écrit :
