### ISSUE TITLE
[CSV import files] URL with http are not supported

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#661]
Les fichiers situés dans le fichier joint sont sur un site avec un site en http au lieu de https
La procédure n'aboutit donc pas
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
[SIMM.csv](https://github.com/GrottoCenter/Grottocenter3/files/7589894/SIMM.csv)

**Comment by Clm-Roig** [comment]
PR soumise ici : https://github.com/GrottoCenter/Grottocenter3/pull/664
