### ISSUE TITLE
[CSV import files] No end, documents are not created

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#662]
Pour le fichier csv ci-dessous, le processus se déroule normalement mais je n'abouti pas à un csv avec les erreurs ou a un csv avec la liste des documents créés. 
Le processus s’arrête et je me retrouve devant le bouton IMPORT sur lequel je peux cliquer de nouveau
[usania.csv](https://github.com/GrottoCenter/Grottocenter3/files/7589943/usania.csv)
Les documents n'ont pas  été créés mais quand je souhaite relancer l'import l'application depuis le début, l'application me dit qu'ils existent déjà.

**Comment by Clm-Roig** [comment]
Chez moi ça a l'air de fonctionner, j'ai fait 4 numéros avec upload sur Azure sans souci. C'est juste assez long, il faut compter 5 secondes par fichier le temps que ça le DL puis l'upload sur Azure. 

Je peux éventuellement supprimer toutes les entrées pour ces docs là et tu refais un test ? Par paquet de 50 par exemple, histoire que ça ne dure pas trop longtemps.

**Comment by urien** [comment]
Ok.. je le fait demain

Le mar. 23 nov. 2021 à 22:30, Clément Roig ***@***.***> a
écrit :

**Comment by urien** [comment]
En fait si on reviens sur la fenêtre avec le bouton "télécharger" le processus se poursuit et les documents sont bien créés. Le fait de recliquer sur "télécharger" relance le processus et cela créé les documents autant de fois qu'on clique sur "télécharger"

**Comment by Clm-Roig** [comment]
C'était un problème avec AWS qui n'acceptait pas les requêtes trop "grosses" (probablement quelques Mo) alors qu'on a besoin d'uploader des fichiers jusqu'à 100Mo. C'est corrigé !
