### ISSUE TITLE
[CSV import file] Parent document is not used

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#663]
Pour le fichier suivant la création des documents s'est bien passée et l'import des fichiers est très rapide. C'est très agréable à utiliser

Mais deux lignes concernent des issues qui sont déclarées comme associées à la collection 22006
Cette information ne semble pas avoir été enregistrée car elle ne figure pas dans la page du document créé
https://beta.grottocenter.org/ui/documents/130786

Ni dans la collection
https://beta.grottocenter.org/ui/documents/22006

[Bulgarian Federation of Speleology.csv](https://github.com/GrottoCenter/Grottocenter3/files/7590046/Bulgarian.Federation.of.Speleology.csv)

**Comment by Clm-Roig** [comment]
Actuellement, pour le parent, on cherche via son titre et nom via son ID. Quel fonctionnement te conviendrait le mieux ? Je peux changer très facilement.

**Comment by urien** [comment]
L'id c'est beaucoup plus simple, surtout qu'on a des doublons

Le mar. 23 nov. 2021 à 22:38, Clément Roig ***@***.***> a
écrit :
