### ISSUE TITLE
[DB] Cleanup the document table

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#671]
Dans la table des documents nous avons une liste de collections et de numéros qui nous ont été fournis par la bilbiothèque Suisse.
Mais dans ces données il y a un certain nombre de doublon.
Un fichier avec les id des documents à supprimer (cet id devant également permettre de supprimer les documents ayant cet id dans la colonne document parent) est disponible sur Slack dans le chanel Database

**Comment by Clm-Roig** [comment]
C'est fait. Je vais mettre à jour Elasticsearch manuellement pour que le changement soit bien visible dans les outils de recherche.
