### ISSUE TITLE
[Search] Pbs with issues

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#682]
Quand je cherche une issue pour l'indiquer comme document parent d'un article, la recherche me donne ce que je cherche
![image](https://user-images.githubusercontent.com/1165144/145682275-cfcd7609-847c-4acd-9e0c-0b0b0574f0d2.png)
Mais quand je sélectionne la proposition qui me convient (ici Spelunca 114 [issue])
Il me propose autre chose et l'id n'est pas indiquée, le document parent n'est pas associé à l'article lorsque je valide
![image](https://user-images.githubusercontent.com/1165144/145682328-8ee26bf1-9534-44a0-a97c-9206c2ec8f8c.png)

**Comment by urien** [comment]
J'ai ce pb avec d'autre issues de Spelunca mais aussi EcoKarst...

**Comment by urien** [comment]
Ce qui est sélectionné, en qui conduit à une erreur, est la concaténation du nouveau label (Spelunca 144 dans l'exemple) et de l'ancienne valeur de ce label (No 114 (juin 2009) dans l'exemple)

**Comment by urien** [comment]
Il me semble que c'est un problème dans l'indexation
Si je fais la recherche sur Spéléalpes comme ci dessous cela ne donne rien
![image](https://user-images.githubusercontent.com/1165144/146214663-de563868-7019-42df-85f5-d679d6b8d142.png)
Alors que la fiche existe bien
https://beta.grottocenter.org/ui/documents/24644

**Comment by Clm-Roig** [comment]
Concernant le Spélélpes, il est marqué comme "deleted" dans la base de données et n'est donc pas recherchable. 

Ensuite, pour le Spelunca 114, effectivement on concatène le nom (Spelunca 114) avec le champ issue (No 114 (juin 2009)). 
Qu'est-ce qu'il te faudrait comme solution ? Que doit afficher l'application dans ce cas-là ?

**Comment by urien** [comment]
Ok,

Merci ... J'ai fait des noeuds pour rien cela fonctionne très bien... pour les documents qui ne sont pas supprimés
