### ISSUE TITLE
[import CSV] error with document type "https://ontology.uis-speleo.org/ontology/#AutorizationToPublish"

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#683]
Je souhaite importer les fichiers qui contiennent l'autorisation de publication sur Grottocenter fournie par les auteurs.

Si je déclare le document de type https://ontology.uis-speleo.org/ontology/#AutorizationToPublish j'ai une erreur à la dernière étape (ReferenceError: typeDate is not defined). Si je change pour le type http://id.loc.gov/vocabulary/marcgt/art l'import aboutit

**Comment by Clm-Roig** [comment]
Est-ce que tu peux réessayer stp ? Je crois que ça venait d'un espace en trop avant l'url de ce type de fichier dans la base de données, je viens de le corriger.

**Comment by urien** [comment]
Je viens de le faire et j'ai la même erreur.
Je te mets le fichier que j'utilise
[autorisation1.csv](https://github.com/GrottoCenter/Grottocenter3/files/7728046/autorisation1.csv)

**Comment by Clm-Roig** [comment]
Je vais déployer l'API pour qu'on voit la véritable erreur. L'erreur renvoyée dans le CSV d'échec est une faute de frappe que j'ai corrigé.

**Comment by Clm-Roig** [comment]
C'est bon ça marche, c'était bien l'erreur dans la BD que j'avais corrigé... sans avoir sauvé la modif ! Tu trouveras les 3 documents dans la liste des documents en attente de validation sur la prod @urien :slightly_smiling_face:
