### ISSUE TITLE
[SECURITY] Origin check for DELETE requests

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#689]
Il faudrait que l'API interdise de faire toutes les opération de DELETE en dehors de l'application Grottocenter

**Comment by Clm-Roig** [comment]
Le problème de quoi exécute l'action ("quoi" au sens notre application, un hacker dans son coin etc.), c'est invérifiable facilement : https://stackoverflow.com/questions/60354919/restrict-api-access-in-node-js-express

2 cas possibles : 
- un développeur / hacker vraiment déterminé arrivera quasiment toujours à contourner nos sécurités, le web est comme ça par définition.
- un utilisateur lambda par contre, on peut éventuellement ajouter une vérification du header `Origin` qui est envoyé automatiquement dès qu'on effectue une requête HTTP. Il a alors pour valeur "beta.grottocenter.org" lorsque la requête provient de notre client.

**Comment by urien** [comment]
Pour aujourd'hui cela me semble bien

**Comment by bsoufflet** [comment]
Merci pour la recherche @Clm-Roig :)
Je propose donc de coupler le check du header Origin pour les requetes DELETE à une règle express-rate-limit custom pour le cas des DELETE (ca semble possible d'après la doc). On autoriserait (pour une meme adresse IP) un maximum de 10 delete sur une fenetre de 2h.
@urien : tu en penses quoi ? Ca ne risque pas de bloquer des modérateurs comme Bernard qui font du nettoyage à grande échelle ?

**Comment by Clm-Roig** [comment]
On peut ne pas appliquer cette règle aux modérateurs si besoin, le système de droits dans la BD couplé à express-rate-limit le permet plutôt facilement.

**Comment by bsoufflet** [comment]
Ce serait top !!!
Alors la règle serait pour moi : 
- maximum 1 delete par fenetre de 12h pour les utilisateurs non modérateur. 
- maximum  20 delete par fenetre de 1h pour les modérateurs / admin

**Comment by urien** [comment]
Oui comme cela on sécurise bien nos données.

**Comment by Clm-Roig** [comment]
Je vais implémenter ça sur le delete de caves #688 tout de suite :slightly_smiling_face:
