### ISSUE TITLE
[MAP] For the map, return only the caves which are networks

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#690]
Actuellement on affiche l'ensemble des caves lorsqu'on sélection le bouton réseau. Il faudrait que ne soient affichées que les caves qui sont des réseaux (caves associés à plus d'une entrance).

**Comment by Clm-Roig** [comment]
Je rajoute quelques précisions. L'appel à l'API effectué est le suivant : 
`GET api/v1/geoloc/cavesCoordinates` 

A voir s'il faut pas changer l'URL de la route par `geoloc/networksCoordinates` au passage (et donc l'url appelé par le client également)

**Comment by urien** [comment]
Tu as sans doute raison... Mais cela fait du boulot en plus. Cela éviterait d'y revenir.
