### ISSUE TITLE
[ENTRANCE DOCUMENTS] Add informations

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#691]
Pour la présentation des documents associés à une entrance Clément Rz a besoin d'afficher les informations suivantes :

Nom des document
Id des document
Licence de chaque document
URL de la licence de document
Label des fichiers associés a chaque document
URL des fichiers associés à chaque document

**Comment by ClemRz** [comment]
Voici un peu plus de precisions:

```
entry
    |_ documents
        |_ document
            |_ id (number)
            |_ titles
                |_ (first element) (string)
            |_ type
                |_ name (string)
            |_ files
                |_ file
                    |_ fileName (string)
                    |_ completePath (string)
            |_ license
                |_ name (string)
                |_ url (string)
```
