### ISSUE TITLE
[DOCUMENT VALIDATION] Bug

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#696]
J'ai un document qui apparait ciomme devant être validé

![image](https://user-images.githubusercontent.com/1165144/147076663-6fafff07-9f84-42c4-9e84-c200a984bce4.png)
https://beta.grottocenter.org/ui/documents/68585

Et il n'apparait pas dans la liste des documents à valider
![image](https://user-images.githubusercontent.com/1165144/147076789-75656c44-6bbf-4cca-8de3-6335a903ca14.png)

**Comment by urien** [comment]
Cela semble concerner tous ces documents
![image](https://user-images.githubusercontent.com/1165144/147077130-c04af738-e5dd-44d4-b81b-37032b2675f5.png)

La liste est visible ici https://beta.grottocenter.org/ui/documents/21403

**Comment by urien** [comment]
J'ai aussi le mêe pb avec https://beta.grottocenter.org/ui/documents/90522

**Comment by Clm-Roig** [comment]
On a actuellement 27 documents (ceux que tu as cité notamment) qui sont marqué comme `validé` mais avec du contenu dans `modified_doc_json`, c'est-à-dire avec une modification en attente... 

Je peux modifier à la main ces 27 documents mais dans quel sens ? Supprimer les potentielles modifications ? Ou les "dévalider" ? 

A l'avenir, il faudra être vigilant et trouver d'où vient ce bug... Il doit y avoir un cas limite où on change un des 2 champs sans toucher à l'autre (alors qu'on devrait).

**Comment by urien** [comment]
Tu peux les valider ?
Je suis ennuyé car j'ai l'impression de faire la même chose quand cela passe et quand cela reste bloqué. Je vais m'y remettre et les faire un par un en validant a chaque fois pour essayer de trouver un cas qui ne passe pas

**Comment by Clm-Roig** [comment]
Ok, je valide et je supprime donc les modifs en attente pour les documents suivants : 
68588
95
132846
132853
68584
68587
68599
68602
68603
68604
68605
68606
68608
68607
69076
69078
68585
68609
68583
69077
90522
129277
129330
129332
129351
129423
132838

Ou bien si tu préfères leurs titres : 
N° 23 (2008)
N° 22 (2007)
Manque N° 24 (200X)
N° 26 (2009)
N° 27 (2010)
N° 28 (2010)
N° 31 (2012)
N° 32 (2012)
N° 33 (2013)
N° 34 (2013)
N° 35 (2014)
N° 36 (2014)
N° 37 (2015)
N° 38 (2015)
N° 39 (Janvier 2016)
N° 41 (Janvier 2017)
Bibliography
L’ANAR BULL’
L’ANAR BULL’.
L'ANAR Bull'
L'ANAR Bull'
L’ANAR BULL’
L’ANAR BULL’
ANAR Bull' N° 40
ANAR Bull n°18
ANAR Bull n°25
ANAR Bull n°10

**Comment by urien** [comment]
Merci,
avec cela je vais vérifier et mettre dans l'état qui convient

**Comment by Clm-Roig** [comment]
C'est fait, je ferme. Si tu veux que je vérifie la base de données au fur et à mesure de tes tests, on peut discuter sur Slack dès maintenant :slightly_smiling_face:

**Comment by urien** [comment]
J'ai compris le bug
C'est quand un article devient une issue et qu'il reste un numéro de page (page de fin). Cela plante le processus de validation.
Quand on transforme un article en issue il faut qu'il n'y ai aucun numéro de page pour que l'api fasse le traitement correctement

**Comment by Clm-Roig** [comment]
J'ouvre une nouvelle issue pour récapituler ce problème uniquement.
