### ISSUE TITLE
[DOC Show children] Grandchildren aren't visible

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#698]
Dans une collection les petits enfants n'apparaissent pas
La collection
https://beta.grottocenter.org/ui/documents/22168
Le numéro https://beta.grottocenter.org/ui/documents/132884 a bien un enfant qui est visible sur sa page mais pas dans la page de la collection
C'est peut être lié au bug repéré pour la validation des documents

**Comment by Clm-Roig** [comment]
Je m'en occupe, je sais où est le souci !
