### ISSUE TITLE
[MASSIF] Return entrances instead of caves

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#701]
Related to / Needed for https://github.com/GrottoCenter/grottocenter-front/issues/303

@urien @bsoufflet  pour l'API, quel serait la représentation idéale pour ce problème, du point de vue d'un utilisateur extérieur de l'API (pour le client on s'adaptera) ?

1) `massif.entrances` et plus de `massif.caves` ? 
2) `massif.caves` et pour chaque cave, `cave.entrances` ? C'est-à-dire qu'on laisse les cavités et réseaux visibles pour tout le monde, mais sur le client on n'affichera que les entrées. 

Quid des networks ? On rajoute `massif.networks` en plus ?

**Comment by urien** [comment]
Pour moi c'est massif.entrance
Et pour les étudiants, s'ils travaillent sur le sujet au mois d'avril on aura besoin de massif.network
