### ISSUE TITLE
[ORGANIZATION] Get entrances instead of caves

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#704]
@urien J'ai besoin de plus d'informations sur cette fonctionnalité. 
Actuellement, en base de données, une organisation explore et "parraine" (ou "est partenaire de") une cavité. Si on veut afficher des entrées, ça va demander un travail supplémentaire : 
- Soit de chercher parmi les cavités celles qui sont juste des cavités à une entrée (ce qu'on appelle donc une cavité).
- Soit de modifier le modèle de données pour explorer et parrainer des entrées plutôt que des cavités. 

Qu'en penses-tu ?

**Comment by urien** [comment]
Il faut choisir la solution la moins coûteuse en temps. On va utiliser postgis pour associer automatiquement les entrées a un massif, on espère que des étudiants vont s'en occuper...
Dans l'attente la solution 1 que tu proposes est sans doute la plus rapide à mettre en oeuvre. Il faudrait que le lien permette de rejoindre la page de l'entrée qui est déjà complète et pourra être éditée

**Comment by Clm-Roig** [comment]
Je pense que c'est la meilleure chose à faire aussi. Je peux aussi mettre les réseaux.
Je synthétise histoire d'être sûr. En BD, une organisation parraine des "caves", donc soit des réseaux soit des cavités à une seule entrée.

On aurait donc, pour une organisation :
- `exploredEntrances` --> les entrées rattachées à des cavités à une seule entrée
- `exploredNetworks` --> les réseaux (cavités à plusieurs entrées). 
(même choses pour les entrances & networks "parrainés", `partneredEntrances` & `partneredNetworks`, ce qui fait 4 attributs au total)

ça te paraît bon ?

**Comment by Clm-Roig** [comment]
Je vais créer une page Wiki sur toute cette nomenclature, on a quand même un vocabulaire particulier désormais ^^ J'y ajouterai aussi l'équivalence grotto <=> organization dedans par exemple.

**Comment by urien** [comment]
Merci, cela me semble clair.
Les membres de l'association commencent à percevoir les problèmes entre entrance/cave et cavité/reseau. Et on a souvent des questions des étudiants : le wiki sera utile

**Comment by Clm-Roig** [comment]
La page wiki est en ligne ici => https://github.com/GrottoCenter/Grottocenter3/wiki/Vocabulary

Je m'attelle au sujet initial de cette issue de ce pas !
