### ISSUE TITLE
[TESTS] Add more tests

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#711]
Clément a commencé à mettre en place de nombreux tests.
Il convient de finaliser ce travail afin de disposer de l'ensemble des tests nécessaires

**Comment by Clm-Roig** [comment]
Doublon avec https://github.com/GrottoCenter/Grottocenter3/issues/634
Je ferme et je corrige sur le doc des développement 2022.

**Comment by Clm-Roig** [comment]
Je ré-ouvre, cette issue a totalement du sens en fait. Il faut juste préciser quelques éléments. Maintenant que #634 est résolue, il s'agit de préciser quel "taux de test" on attend. Ou bien quelles fonctionnalités doivent être testées en priorité ? Sinon cette issue mettra énormément de temps à être résolue.

**Comment by Clm-Roig** [comment]
Je ferme, c'est trop vague, on rouvrir des issues ciblées pour certains tests à mettre en place en priorité si besoin (plutôt que de continuer ici).
