### ISSUE TITLE
[IMPORT FILE] Server error when importing a csv file for a dataset document

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#712]
**Describe the bug**
J'arrive à mettre à jour le seul document de type dataset mais quand je souhaite lui associer un fichier de type csv j'ai un message d'erreur serveur

**To Reproduce**
1. télécharger le fichier csv 
[snokarst_18012022_data.csv](https://github.com/GrottoCenter/Grottocenter3/files/7891915/snokarst_18012022_data.csv)
2. Editer le document https://beta.grottocenter.org/ui/documents/edit/130207
3. rajouter le fichier csv (licence ouverte, la licence est écrite dans le fichier
4. bandeau rouge"erreur serveur"

**Expected behavior**
Il semble que ce soit une erreur côté back compte tenu du message, cela semble associé au fichier csv car j'ai le même probleme si je déclare le document de type texte

![image](https://user-images.githubusercontent.com/1165144/150007654-892ce713-538a-4f71-a7c1-f1c1f62f64e0.png)

**Comment by Clm-Roig** [comment]
Je viens d'effectuer les manips que tu décrivais dans "Steps to reproduce" et ça a marché, étrange... Je ferme donc pour le moment concernant ce document, n'hésite pas à réouvrir une issue si besoin :)
