### ISSUE TITLE
[Document] Add licences 

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#718]
**Is your feature request related to a problem? Please describe.**
Le CDS 69 et le Club des Vulcains ont donné leur accord pour que leurs publications soient intégrées dans le BBS sur Grottocenter mais ils souhaitent que ce soit sous la licence CC BY NC SA
https://creativecommons.org/licenses/by-nc-sa/4.0/

**Describe the solution you'd like**
Il faudrait donc rajouter cette licence dans la table des licences

Mais plutot que de revenir sur ce sujet sans cesse ou pourrait aussi ajouter 
CC BY NC (pour le bulletin de l'UIS)
https://creativecommons.org/licenses/by-nc/4.0/

CC BY ND
https://creativecommons.org/licenses/by-nd/4.0/

**Comment by Clm-Roig** [comment]
Pour confirmation, ces licences ne sont pas copyrightées ? C'est pour les rentrer dans la BD avec la bonne valeur sur l'attribut `isCopyrighted`.

**Comment by urien** [comment]
Oui je pense. Je n'ai pas en tete le nom des tables, mais je crois que c'est cela. C'est pour pouvoir utiliser ces licences quand on fait un import csv ou quand on associe un fichier à un document.. Avec ces licences je pense qu'on sera tranquille. CC n'en propose pas d'autres
