### ISSUE TITLE
[CAVE SEARCH] Search a cave with one entrance

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#720]
**Describe the bug**
Nous avons besoin d'étre capable de rechercher les cavités qui ont plus d'une entrée afin de reconnaitre les réseaux mais il est nécessaire de pouvoir également une recherche sur l'ensemble des caves afin de pouvoir sélectionner une cave avec une entrée et lui associer une seconde entrée. Actuellement cela semble impossible, dans la page de création d'une cavité, si on souhaite l'associer à un réseau il n'est possible que de sélectionner un réseau existant, ce qui empêche d'en créer un nouveau

**To Reproduce**
Sur la PR côté front créer une cavité en demandant de l'associer à un réseau existant. Faire une recherche sur "Mègevette" cela fonctionne car c'est une cave avec plusieurs entrées. Faire une recherche sur "PG 18-5" le résultat ne ressoirt par car c'est une cave avec une seule entrée

La résolution de cette PR est nécessaire pour mettre en production les fonctionnalités de création et d'édition des cavités

**Comment by Clm-Roig** [comment]
Ce n'est pas un problème de l'API, la recherche de cave existe déjà. 

C'est plutôt la [PR front](https://github.com/GrottoCenter/grottocenter-front/pull/56) qu'il ne fallait pas valider en l'état. Sur cette PR, on parlait depuis le début de "linked to a network" ou "not linked to a network". Il aurait fallut un 3ème choix qui est "link to an existing cave to create a network" si je comprends bien ton problème.

**Comment by urien** [comment]
En fait les utilisateurs ne savant pas si le réseau existe ou pas dans Grottocenter.
Le plus simple étant de leur proposer uniquement deux possibilités : créer une cavité seule ou créer une cavité qui doit être associée à un réseau, que celui-ci existe ou pas dans Grottocenter. Et dans ce cas ou leur propose de choisir une cave parmis toutes cettes qui existent. Est ce que cela se résout uniquement du côté front ?

**Comment by Clm-Roig** [comment]
Oui c'est uniquement côté front. Celui-ci demandera à l'API de chercher dans les "caves" au lieu des "networks".

Par contre la formulation est peut-être à peaufiner dans le formulaire, en ajoutant une phrase d'aide pour indiquer la création implicite du réseau par exemple.

**Comment by urien** [comment]
Ok, cette issue doit être fermée
