### ISSUE TITLE
 [DOC edition] Parent edition doesn't display name correctly

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#721]
**Describe the bug**
Lors de l'édition d'un document déjà modifié, le nom du document parent est incomplet (cf screenshot plus bas).

**Steps to reproduce**
1. Créer un document avec un document parent étant une issue.
2. Éditer le document.
3. Changer son document parent pour une autre issue.
4. Ré-éditer le document : le nom du parent ne s'affiche pas correctement.

**Expected behavior**
L'API devrait renvoyer toutes les infos nécessaires pour afficher le nom du parent correctement (title + issue ?).

**Screenshots**
![image](https://user-images.githubusercontent.com/20704943/156755124-480a5877-e5ce-44a5-9508-48d616870349.png)

**Comment by Clm-Roig** [comment]
@urien j'ai récapitulé ci-dessus ce que tu m'avais dit sur cette issue. C'est un peu flou pour moi, je me demande si le **Bug 1** n'est pas le même que le **Bug 2** ? 

En gros, est-ce que toute cette issue n'est pas qu'un souci de donnée manquante quand au document parent ? (et donc d'affichage incomplet).

**Comment by urien** [comment]
Je ne sais pas, sans doute que si. En fait quand on fait la recherche d'un parent (pour une fiche qu'on édite) on arrive a bien sélectionner le bon parent mais ensuite quand on souhaite éditer la fiche modifiée, dans le processus de validation, on se rend compte qu'on a une valeur null qui est stockée et derrière cela plante le processus de validation

**Comment by Clm-Roig** [comment]
Après avoir fait quelques tests, le `null` n'est qu'un problème d'affichage. L'id du document parent est bien stocké, même après édition.

> cela plante le processus de validation

Je n'ai pas réussi à reproduire ce bug-là, tu pourras essayer à l'occasion et me transmettre la procédure à suivre pour reproduire s'il te plaît ?

**Comment by urien** [comment]
Je viens de le faire. J'ai demandé à éditer ce document
![image](https://user-images.githubusercontent.com/1165144/156893691-7c350d0c-084d-45d2-8279-128c83b8ad75.png)
Et j'ai demandé à ce que ce soit un article et pas un numéro. Je l'ai associé à un document parent de type numéro
Le processus de validation a planté avec la fenetre de validation qui réapparait. Si je rafraichi la page le document n'est plus à valider. Et quand je vais sur la fiche du document il est en attente de validation
![image](https://user-images.githubusercontent.com/1165144/156893770-78d688a6-2f02-4ce1-9b13-80e36310b0c7.png)

**Comment by Clm-Roig** [comment]
J'ai trouvé ! Lorsque tu as transformé le numéro en article, l'attribut `issue` n'a pas été supprimé. De ce fait, quand on valide le document, on se retrouve avec un Article avec une valeur dans `issue`... ce qui est interdit par un trigger dans la BD ! Seuls les `Issue` et les `Book` ont le droit d'avoir un attribut "issue".

**Comment by Clm-Roig** [comment]
Je transfère sur une autre issue ce nouveau bug.
