### ISSUE TITLE
[ERRORS] Rewrite error responses

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#725]
**Is your feature request related to a problem? Please describe.**
The error responses sent are not properly formatted. Moreover, the responses try to use Sails HTML views.

**Describe the solution you'd like**
- Delete the error pages in /views folder.
- Rewrite the logic of all error responses. For example, I'm not sure this is a good idea : 

```js
// Only include errors in response if application environment
// is not set to 'production'.  In production, we shouldn't
// send back any identifying information about errors.
if (sails.config.environment === 'production') {
  data = undefined;
}
```
`data` is useful for the user and doesn't contain sensitive information. For example, here is some `data` values:
`You are not authorized to create a cave.`
`You are not authorized to view this sensible entrance.`

**Comment by Clm-Roig** [comment]
This can in coordination with #707 for example.

**Comment by bsoufflet** [comment]
I agree with that as an open source app we can display a little more in our error message to users :)
