### ISSUE TITLE
[IMPORT CSV] Import work but impossible to merge

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#745]
**Describe the bug**
Voila le fichier que je souhaite importer. C'est un article que je souhaite associer à sa revue. Je vais avoir de gros volumes de traitements de ce type à faire (rajouter l'id dans la colonne document parent)
[test.csv](https://github.com/GrottoCenter/Grottocenter3/files/8383446/test.csv)

L'import se passe bien et le fichier est déclaré comme étant un doublon
Dans le tableau de gestion des doublons les valeurs ne sont pas correctes
id indefined et parent null
![image](https://user-images.githubusercontent.com/1165144/160913891-caad1b92-ad37-4604-8bc8-7b905ea2ef66.png)

Le merge ne fonctionne pas et il est impossible de supprimer

**To Reproduce**
Importer le fichier test.csv puis aller dans le tableau de gestion des doublons pour le selectionner ou le supprimer

**Comment by urien** [comment]
Message d'erreur : [CORS Missing Allow Origin]()

**Comment by Clm-Roig** [comment]
> Message d'erreur : CORS Missing Allow Origin

Les erreurs de CORS ne sont pas utiles pour débugguer. Souvent elles disparaissent en réessayant et sont indépendantes du bug rencontré. 

Il y a quand même un problème, l'id undefined c'est vraiment pas normal.

**Comment by Clm-Roig** [comment]
C'est l'absence de valeur dans la colonne dc:language qui cause l'erreur. Normalement la langue est obligatoire... 

Tu veux que je travaille à gérer ce cas particulier ?

**Comment by Clm-Roig** [comment]
J'ai rien dit, ce n'est pas forcément obligatoire. Mais c'est mal géré dans le cas où la valeur n'est pas fournie dans le CSV.

**Comment by urien** [comment]
Je viens de faire un test avec le même fichier en rajoutant la langue. Le fichier passe bien mais ce que je mets dans la colonne dct:source et qui est l'identifiant du document parent n'est pas utilisé : une fois le merge réalisé le document n'est pas associé à son document parent.
C'est l'usage que je souhaite faire de cet outil : rajouter l'indication du document parents afin d'associer les articles à leur revue

**Comment by urien** [comment]
Je le mets ici mais cela relève d'un problème différent. Je souhaite faire des tests pour les cavités. J'utilise le fichier ci-dessous, les tests sont passés mais lors de l'import cela plante avec le message "ReferenceError: value is not defined". Je ne pense pas qu'un champ obligatoire ne soit pas renseigné.
[V4.csv](https://github.com/GrottoCenter/Grottocenter3/files/8402821/V4.csv)
[importGCfailure(4).csv](https://github.com/GrottoCenter/Grottocenter3/files/8402822/importGCfailure.4.csv)

**Comment by Clm-Roig** [comment]
> Je le mets ici mais cela relève d'un problème différent. Je souhaite faire des tests pour les cavités. J'utilise le fichier ci-dessous, les tests sont passés mais lors de l'import cela plante avec le message "ReferenceError: value is not defined". Je ne pense pas qu'un champ obligatoire ne soit pas renseigné. [V4.csv](https://github.com/GrottoCenter/Grottocenter3/files/8402821/V4.csv) [importGCfailure(4).csv](https://github.com/GrottoCenter/Grottocenter3/files/8402822/importGCfailure.4.csv)

Je préfère que tu ouvres une nouvelle issue s'il te plaît. C'est extrêmement dur à débugguer comme fonctionnalité, il faut que je me concentre que sur un problème à la fois :slightly_smiling_face:

**Comment by Clm-Roig** [comment]
> Ce que je mets dans la colonne dct:source et qui est l'identifiant du document parent n'est pas utilisé : une fois le merge réalisé le document n'est pas associé à son document parent. 

`dct:source` est utilisé pour la colonne `identifier` de Grottocenter.
Pour le parent, c'est `dct:isPartOf` qui est utilisé.

**Comment by Clm-Roig** [comment]
J'ai fait quelques tests : 
- dct:isPartOf fonctionne correctement...
- ... mais ça plante après à l'affichage côté client (je créé une issue pour ça)
- le content dans le tableau est toujours vide, je pousse un correctif pour ça 

Je te laisse fermer quand tu auras créer une issue pour ton 2ème problème à propos des entrances, ça te va @urien ?

**Comment by urien** [comment]
Ok

**Comment by urien** [comment]
See https://github.com/GrottoCenter/grottocenter-front/issues/353
