### ISSUE TITLE
[CSV Import] Import cave doesn't work because of name language

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#763]
**Describe the bug**
Lorsque j'importe un fichier csv ayant des données de cavités, par exemple celui qui est ci-dessous j'ai le message d'erreur qui est attaché. A priori tous les champs obligatoires sont bien renseignés.
[importGCfailure(5).csv](https://github.com/GrottoCenter/Grottocenter3/files/8403264/importGCfailure.5.csv)
[V4.csv](https://github.com/GrottoCenter/Grottocenter3/files/8403265/V4.csv)

**Comment by urien** [comment]
Je crois qu'il y a des mélanges dans le code.
J'ai bien eu ce message, du coup j'ai mis un code langue pour la description et pour l'accès à la cavité (sans qu'il n'y ai de textes).
Cela passe mais il y a désormais un autre message.
En fait c'est une contrainte qui ne devrait pas exister si on ne donne pas d'information sur la description et sur la location, ces éléments nedevraient pas être créés
2,"AdapterError: Unexpected error from database adapter: insert or update on table ""t_name"" violates foreign key constraint ""t_name_t_language_fk"""
Il y a une obligation d'indiquer la langue du nom de la cavité ? Ce n'est pas une information fournie par le CSV et cela va être compliqué de le changer. Pour les documents cette obligation n'existe pas

**Comment by Clm-Roig** [comment]
Oui un `name` a toujours une langue normalement. Dans l'absolu je trouve ça logique et indispensable. 

Dans la pratique, on a une langue `-Undefined-` qui concerne 1500 noms sur les 124 000 que compte Grottocenter.

**Comment by urien** [comment]
Avec le CSV tel qu'il est défini je ne peux pas indiquer de langue pour le nom. Est ce que tu peux forcer l'enregistrement en BDD avec Undefined ?

**Comment by Clm-Roig** [comment]
C'est dommage de pas avoir ça mais oui je peux mettre une valeur par défaut

**Comment by Clm-Roig** [comment]
J'ai réfléchi à cette histoire de langue. Tu ne veux pas qu'on ajoute une colonne au CSV @urien ? Je n'aime vraiment pas le fait de créer des cavités avec des noms dont la langue n'est pas définie, on ne devrait même pas pouvoir le faire. 

Qu'est-ce qui nous empêche de rajouter une colonne ? C'est beaucoup de boulot ?

**Comment by urien** [comment]
Il faut que je modifie le modèle Karstlink. Si cela te convient je m'y colle demain

**Comment by Clm-Roig** [comment]
Je veux bien oui, merci ! Je travaille aux autres issues en attendant.

**Comment by urien** [comment]
J'ai mis à jour le fichier modèle qu'on utilise pour alimenter en cavités le module d'import csv. Avec une nouvelle colonne après celle du nom de la cavité. 
https://ontology.uis-speleo.org/example/V4.csv

**Comment by Clm-Roig** [comment]
Je peux avoir le nom de la colonne s'il te plaît ? Je ne trouve rien avec "language"...

**Comment by urien** [comment]
M....
J'ai du foirer un truc, le fichier en ligne n'est pas mis à jour, et je suis au travail
Voila ce qu'il faut utiliser 
[V4.csv](https://github.com/GrottoCenter/Grottocenter3/files/8441660/V4.csv)
La colonne s'appelle rdfs:label/dc:language

**Comment by Clm-Roig** [comment]
ça marche merci

**Comment by urien** [comment]
J'ai repris les csv disponibles en ligne, c'est ok maintenant

**Comment by Clm-Roig** [comment]
Sur le fichier V4.csv, il faut mettre à jour les colonnes / valeurs suivantes : 
karstlink:hasAccessDocument/dc:language / FR
➡️ karstlink:hasAccessDocument/dc:language / FRA

karstlink:hasDescriptionDocument/dc:language / FR
➡️ karstlink:hasDescriptionDocument/dc:language / FRA

La langue c'est "FRA", "FR" c'est le pays. J'avais modifié ça mais Axel l'avait remis, on en a discuté plusieurs fois.

**Comment by Clm-Roig** [comment]
Même chose pour les deux documents exemple: sur Karstlink, tu utilises le format `AAAA-MM-JJ` pour `dct:rights/dct:created` et `dct:rights/dct:modified`.

J'ai adapté le code pour correspondre à ce format de date.
