### ISSUE TITLE
Lien depuis l'info bulle

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#77]
Le lien depuis l'info bulle pointe vers une page qui n'existe pas encore
![screenshot-localhost 8081-2018-05-24-16-59-08](https://user-images.githubusercontent.com/1165144/40494208-971cec1a-5f74-11e8-8ef4-d0aab573c6fb.png)
Est ce qu'on ne ferait pas le lien vers la fiche en cliquant sur le nom de la cavité ?
Dans l'immédiat il faudrait indiquer le lien vers la fiche sur la V2

**Comment by Kurdty** [comment]
A page will be created to display entries (#43)

Waiting for this page, we must link the v2's entry page.

**Comment by aleliberty** [comment]
Le lien vers la fiche v3 est fait.
Reste à finaliser le code de la fiche v3 :)

**Comment by Kurdty** [comment]
Le lien vers la fiche v3 est fait.
Reste à finaliser le code de la fiche v3 :)
