### ISSUE TITLE
Gestion de la région dans la popup sur la carte

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#78]
Quand la région n'est pas indiquée en base de donnée les parenthèses apparaissent mais vides
![screenshot-localhost 8081-2018-05-24-17-13-05](https://user-images.githubusercontent.com/1165144/40494739-dd2465de-5f75-11e8-9e8e-654a808fa508.png)

**Comment by Kurdty** [comment]
I kept in mind that you planned to work on this issue.
I assign it to you to be sure that nobody else can take it ;)

**Comment by bsoufflet** [comment]
@maximenathan : Tu as pu regarder ?

**Comment by bsoufflet** [comment]
@maximenathan ?

**Comment by Clm-Roig** [comment]
It seems to be fixed now, no ?

**Comment by Clm-Roig** [comment]
Je ferme, je ne trouve plus d'entrée avec ce souci. N'hésitez pas à réouvrir si jamais vous avez un exemple qui présente ce problème 🙂
