### ISSUE TITLE
Lien sur /dashboard/map

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#79]
Quand on clique sur map on arrive sur la page /ui/
![screenshot-localhost 8081-2018-05-24-17-24-06](https://user-images.githubusercontent.com/1165144/40495395-667fd92a-5f77-11e8-87a2-39bcac847955.png)
Il faudrait que le lien se fasse sur /ui/map/

**Comment by Kurdty** [comment]
Actually, the behaviour is not yet implemented for this part of breadcrump.

We also have a fix to add to remove the last ">"
