### ISSUE TITLE
[LANGUAGE SEARCH] Limit the number of languages offered

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#801]
**Is your feature request related to a problem? Please describe.**
Actuellement toutes les langues disponibles dans la table t_language sont proposées. Il faudrait limiter les propositions aux langues successibles d'être réellement retenues.

**Describe the solution you'd like**
La recherche sur les langues se fera sur le champ is_prefered.
Le nombre de langues ayant cet attribut a true sera augmenté à partir du fichier ci-dessous qui liste les langues qui sont déclarées langues officielles par les pays
[liste_des langues_officielles_parlées_dans_au_moins_un_pays.csv](https://github.com/GrottoCenter/Grottocenter3/files/8499368/liste_des.langues_officielles_parlees_dans_au_moins_un_pays.csv)

**Comment by Clm-Roig** [comment]
On l'a déjà le composant qui cherche que sur is_prefered, c'est exactement ce qu'on utilisait avant que je fasse la Quick search sur toutes les langues. 

Maintenant il s'agit soit de faire évoluer la liste des "is_prefered" soit de d'utiliser un composant ou l'autre.

**Comment by urien** [comment]
La liste des langues qui sont déclarées langues officielles dans au moins un pays compte plus de 250 lignes. Est ce que la quick search ne pourrait pas faire une recherche dans ces 250 références pour retourner rapidement ce que l'on cherche ?

**Comment by Clm-Roig** [comment]
Il me faut une distinction pour cibler ces langues dans la BD (d'où le is_prefered). Une fois que j'ai l'info stockée dans la BD, oui je peux chercher dessus uniquement.

**Comment by urien** [comment]
Je viens de rajouter le fichier csv avec la liste des id des langues à retenir
