### ISSUE TITLE
[API ENTRANCE] Split the returned datas in two URL

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#803]
**Is your feature request related to a problem? Please describe.**
If we add the data from the observations made in the caves, the entrances page will take a very long time to load.

**Describe the solution you'd like**
The api.grottocenter.org/api/v/entrances/:id page would be replaced by the api.grottocenter.org/api/entrances/:id/explorations/ page which will return the same data. The api.grottocenter.org/api/v/entrances/id page will be retained and declared deprecated. A new page api.grottocenter.org/api/v1/observations/:id will provide basic cave data and data from observations. first, data related to human activities

**Comment by Clm-Roig** [comment]
En accord avec la réunion de hier soir, je ferme au profit de #840. 

Le fait de séparer les données côté client ne concerne pas l'API. On peut éventuellement rajouter ce qui suit sur l'issue côté client. 

Le client fera 2 requêtes pour obtenir une cavité / entrée : 
- Une première avec les informations de base
- Et une deuxième **facultative** déclenchée par l'utilisateur pour charger les observations (éventuellement paginées)
