### ISSUE TITLE
[API] Create / Edit / delete Observations

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#804]
**Is your feature request related to a problem? Please describe.**
For the observations to be searchable and so that we can later view a page of observations, the API must be able to manage these objects.

**Describe the solution you'd like**
Requirements are described here
https://github.com/GrottoCenter/grottocenter-front/issues/411
https://github.com/GrottoCenter/grottocenter-front/issues/412
https://github.com/GrottoCenter/grottocenter-front/issues/413

**Comment by Clm-Roig** [comment]
Qui a les droits de créer / éditer / afficher les observations ? 
- Créer / éditer => utilisateurs ? 
- Afficher => n'importe qui ? (visiteur)

**Comment by urien** [comment]
Oui

**Comment by Clm-Roig** [comment]
Ok je divise en multiples issues, celle-ci est trop vaste :slightly_smiling_face:

**Comment by Clm-Roig** [comment]
C'est divisé, je ferme ici : 

- Count https://github.com/GrottoCenter/Grottocenter3/issues/905
- Get https://github.com/GrottoCenter/Grottocenter3/issues/906
- Create https://github.com/GrottoCenter/Grottocenter3/issues/907
- Delete https://github.com/GrottoCenter/Grottocenter3/issues/908
- Edit https://github.com/GrottoCenter/Grottocenter3/issues/909
- Search https://github.com/GrottoCenter/Grottocenter3/issues/910
