### ISSUE TITLE
[ENTRANCE EDIT] Change cave

### ISSUE THREAD

**Issue by Clm-Roig** [GrottoCenter/Grottocenter3#852]
### Related to https://github.com/GrottoCenter/grottocenter-front/issues/436

Une entrée est liée à une cavité (ou un réseau). L'API doit permettre de déplacer l'entrée vers une autre cavité. 
Route suggérée : 
```js
PATCH entrances/:entranceId/cave/:caveId
```

Cependant un cas particulier doit être traité : que faire d'une cavité orpheline dans le cas d'une cavité à une seule entrée ? On la supprime c'est bien ça ? @urien

**Comment by urien** [comment]
Oui avec le système qu'on utilise désormais en mettant à true un champ is_deleted
