### ISSUE TITLE
[EMAIL NOTIFICATION] send email for new contributions to Leaders

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#868]
Il convient d'envoyer des emails aux leaders, selon les critères qu'ils ont retenus, concernant les ajouts et les modifications intervenues sur la table des Entrances et sur les tables associées à chaque entrance concernée. https://github.com/GrottoCenter/grottocenter-front/issues/463
Si le mel revient en retour il faudrait stocker l'information et la rendre accessible lors de la connexion au compte concerné.

Ce mel comporterait :

- le nom de l'entrée avec un lien vers la fiche de la cavité
- entre parenthèse des informations sur les éléments qui ont été modifiés : 
  1. informations générales (issues des tables t_entrances et t_cave)
  2. localisation
  3. description
  4. équipement
  5. document
  6. historique
  7. commentaire

**Comment by Clm-Roig** [comment]
> Si le mel revient en retour il faudrait stocker l'information et la rendre accessible lors de la connexion au compte concerné.


Qu'entends-tu par "mel revient en retour" ? Le fait que le mail n'ait pas été distribué au destinataire ?

De toute façon, si j'ai bien compris, l'info sera accessible grâce à cette feature non ? => https://github.com/GrottoCenter/grottocenter-front/issues/463

**Comment by urien** [comment]
Oui c'est cela. Il me semble qu'il y a un champ prévu pour cela. de mémoire AWS est attentif a ce qu'il n'y ai pas trop d'erreur dans les mels envoyés et il bloque le service si on a trop de messages en erreur. Si c'est trop compliqué à mettre en place on ne le fait pas, mais ce sera indispensable a un moment

**Comment by Clm-Roig** [comment]
Ok merci pour les précisions. Ça me paraît totalement faisable, pas de problème de ce côté-là.

**Comment by Clm-Roig** [comment]
Je bouge cette issue côté API, ça ne concerne pas le client. C'est l'API qui enverra d'elle-même le mail lorsqu'une modification aura lieu.

**Comment by Clm-Roig** [comment]
Je ferme au profit de #882 qui inclus également l'envoie de mail.
