### ISSUE TITLE
[NOTIFICATIONS] Tables & routes

### ISSUE THREAD

**Issue by urien** [GrottoCenter/Grottocenter3#869]
Une table doit être mise en place et une Api développée afin de stocker les informations qui seront collectée via cette fonctionnalité Front https://github.com/GrottoCenter/grottocenter-front/issues/463

**Comment by urien** [comment]
Le fait qu'une personne perde le status de leader doit conduire a supprimer les lignes qui indiquent les notifications qu'il doit recevoir

**Comment by Clm-Roig** [comment]
Si je résume, on a donc besoin des choses suivantes pour la BD : 
- Table **JCaverMassifSubscription** ➡️ référence les massifs qu'un leader veut surveiller
- Table **JCaverCountrySubscription** ➡️ référence les pays qu'un leader veut surveiller

Ensuite, niveau fonctionnalités de l'API : 
1. POST /api/v1/massifs/:massifId/subscribe ➡️ s'inscrire aux notifications d'un massif
2. DELETE/api/v1/massifs/:massifId/subscribe ➡️ se désinscrire aux notifications d'un massif
3. GET /api/v1/cavers/:caverId/massifs/subscriptions ➡️ obtenir la liste des massifs auxquels un utilisateur est inscrit
4. GET /api/v1/cavers/:caverId/massifs/notifications ➡️ obtenir la liste des notifications liées aux massif auxquels l'utilisateur est inscrit

**(même chose pour les pays évidemment)**

Concernant la route 4., le nombre de notifications va vite croître. Il va donc falloir paginer cette route pour que l'utilisateur demande ses notifications 50par 50 par exemple.

Autre chose, sur quel critère va-t-on construire une notification ? Savoir qu'une cavité a été modifiée, c'est facile : on a l'attribut **is_reviewed** qui stocke la dernière date de modif. Par contre, savoir exactement ce qui a été modifié, il va falloir jongler entre toutes les tables d'historisation "annexes" (ex : h_description et h_location).

**Comment by Clm-Roig** [comment]
Si tu valides l'approche ci-dessus @urien, je divise cette issue en plusieurs issues plus petites.

**Comment by urien** [comment]
Je pense qu'il n'y a pas besoin de pagination. Typiquement un leader sera intéressé par un pays où un massif. Mais il faut que cela fonctionne s'il sélectionné quelques pays ou quelques massifs

**Comment by Clm-Roig** [comment]
Le point 4 c'est la liste des notifications : il va y en avoir beaucoup. 
Tu confonds avec le 3 qui est la liste des "subscriptions" où là, effectivement, il n'y aura que quelques massifs / pays.

**Comment by urien** [comment]
Ce serait très réducteur si on avait que les infos concernant les modifications sur t_entrance.
Le plus important, par ordre décroissant c'est les description, les documents, les localisations, les riggings.

**Comment by urien** [comment]
ok pour les notifications, je comprends

**Comment by urien** [comment]
Est ce que le point 4 ne peut pas être remplacé par caver/id/notifications ?
On va avoir les notifications des modérateurs pour les documents a valider, les notifications pour les usées quand leurs documents sont validés ou refusés, sans doute des notifications pour les admins

**Comment by Clm-Roig** [comment]
Le rôle de la personne est pris en compte de par le son token d'authentification qu'il envoie à l'API. 
Par contre, je n'ai pas du tout prévu les notifications pour les validations / refus de docs... 

Si le système de notifications est amené à grossir, on peut effectivement n'avoir qu'un seul point d'entrée qui est `api/v1/notifications` et qui retourne TOUTES les dernières notifications de l'utilisateur qui a appelé cette route.

**Comment by urien** [comment]
C'est cela, pour l'instant ce sont des notifications aux leaders pour les cavités d'un pays ou d'un massif mais avec la perspective que cela évolue.

**Comment by Clm-Roig** [comment]
Je ferme au profit de #880, #881 et #882 qui sont un résumé de notre conversation et qui divisent cette fonctionnalité en 3 plus petites.
