### ISSUE TITLE
Dynamization of the numbers of 'Grottocenter numbers' section

### ISSUE THREAD

**Issue by Kurdty** [GrottoCenter/Grottocenter3#9]
Numbers have to be read from backend API and periodically updated.

Action plan:
- Create necessary API entries
- Enhance React components to manage refresh using Redux workflow

**Comment by Kurdty** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dynamization of the numbers of 'Grottocenter numbers' section](https://trello.com/c/p0WUZlmj/109-dynamization-of-the-numbers-of-grottocenter-numbers-section)

**Comment by Didine74** [comment]
https://github.com/GrottoCenter/Grottocenter3/pull/21
